package view;

import java.awt.Dimension;
import model.bean.Veiculo;
import connection.TesteBanco;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import model.bean.Aluguel;
import model.bean.Cliente;
import model.bean.Validadores;
import model.bean.Veiculo;
import model.bean.validaCPF;
import model.dao.AluguelDAO;
import model.dao.ClienteDAO;
import model.dao.VeiculoDAO;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author total
 */
public class jif_cadastroVeiculo extends javax.swing.JInternalFrame {

    /**
     * Creates new form jif_cadastroMotorista
     */
    
    jif_pneu pneu = new jif_pneu();
    
    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    public void johnson(){
        Cliente c = new Cliente();
        ClienteDAO cd = new ClienteDAO();
       
        c.setCnpj(jft_cnpj.getText());
         
        String retorno3 = "mano";
        try {            
            ResultSet rs = null;
            retorno3 = cd.buscarCnpj1(c.getCnpj());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Erro no select completo de veiculo" + ex);
        }
        jtf_nomeEmpresa.setText(retorno3);
        
    }
     Validadores validaT = new Validadores();

    public boolean ifNull(){
        if(jtf_placa.getText().equals("")){
            return false;
        }
        if(jtf_chassi.getText().equals("")){
            return false;
        }
        
        if(jtf_tipo.getText().equals("")){
            return false;
        }
        
        if(jtf_nomeEmpresa.getText().equals("")){
            return false;
        }
     
        
        if( jft_cnpj.getText().equals("  .   .   /    -  ")){
            return false;
        }
        if(jft_ano.getText().equals("")){
            return false;
        }
      
        
        if(jtf_marca.getText().equals("")){
            return false;
        }
        
        if(jtf_quilometragem.getText().equals("")){
            return false;
        }
       
        
        return true;
    }
    
    public void limpar() {
        jtf_placa.setText("");
        jtf_chassi.setText("");
        jft_cnpj.setText("");
        jtf_marca.setText("");
        jft_ano.setText("");
        jtf_quilometragem.setText("");
        jtf_tipo.setText("");
        jtf_nomeEmpresa.setText("");
        jtf_cor.setText("");
        jtf_modelo.setText("");
    }

    public jif_cadastroVeiculo() {

        initComponents();
        jtf_idCli.setVisible(false);
        jtf_idAlug.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jpl_opcoes = new javax.swing.JPanel();
        jbn_fechar = new javax.swing.JButton();
        jbn_limpar = new javax.swing.JButton();
        jbn_cadastro = new javax.swing.JButton();
        jbn_novo = new javax.swing.JButton();
        jbn_pneu = new javax.swing.JButton();
        jlb_placa = new javax.swing.JLabel();
        jtf_chassi = new javax.swing.JTextField();
        jlb_cor = new javax.swing.JLabel();
        jtf_placa = new javax.swing.JTextField();
        jft_cnpj = new javax.swing.JFormattedTextField();
        jlb_cnpj = new javax.swing.JLabel();
        jlb_marca = new javax.swing.JLabel();
        jtf_marca = new javax.swing.JTextField();
        jlb_ano = new javax.swing.JLabel();
        jft_ano = new javax.swing.JFormattedTextField();
        jlb_quilometragem = new javax.swing.JLabel();
        jtf_quilometragem = new javax.swing.JTextField();
        jtf_modelo = new javax.swing.JTextField();
        jlb_modelo = new javax.swing.JLabel();
        jlb_tipo = new javax.swing.JLabel();
        jtf_tipo = new javax.swing.JTextField();
        jlb_alugados = new javax.swing.JLabel();
        jrb_sim = new javax.swing.JRadioButton();
        jrb_nao = new javax.swing.JRadioButton();
        jtf_nomeEmpresa = new javax.swing.JTextField();
        jbn_buscar = new javax.swing.JButton();
        jtf_cor = new javax.swing.JTextField();
        jlb_chassi = new javax.swing.JLabel();
        jtf_idCli = new javax.swing.JTextField();
        jtf_idAlug = new javax.swing.JTextField();

        jToggleButton1.setText("jToggleButton1");

        setForeground(java.awt.Color.white);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro Veiculo"));

        jpl_opcoes.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jpl_opcoes.setToolTipText("Opções");

        jbn_fechar.setText("Fechar");
        jbn_fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_fecharActionPerformed(evt);
            }
        });

        jbn_limpar.setText("Limpar");
        jbn_limpar.setEnabled(false);
        jbn_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_limparActionPerformed(evt);
            }
        });

        jbn_cadastro.setText("Cadastrar");
        jbn_cadastro.setEnabled(false);
        jbn_cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_cadastroActionPerformed(evt);
            }
        });

        jbn_novo.setText("Novo");
        jbn_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_novoActionPerformed(evt);
            }
        });

        jbn_pneu.setText("Pneu");
        jbn_pneu.setEnabled(false);
        jbn_pneu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_pneuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpl_opcoesLayout = new javax.swing.GroupLayout(jpl_opcoes);
        jpl_opcoes.setLayout(jpl_opcoesLayout);
        jpl_opcoesLayout.setHorizontalGroup(
            jpl_opcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpl_opcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpl_opcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbn_fechar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbn_limpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbn_novo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbn_cadastro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbn_pneu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpl_opcoesLayout.setVerticalGroup(
            jpl_opcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpl_opcoesLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jbn_novo)
                .addGap(27, 27, 27)
                .addComponent(jbn_cadastro)
                .addGap(18, 18, 18)
                .addComponent(jbn_limpar)
                .addGap(18, 18, 18)
                .addComponent(jbn_pneu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jbn_fechar)
                .addContainerGap())
        );

        jlb_placa.setText("Placa:");

        jtf_chassi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_chassi.setEnabled(false);
        jtf_chassi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_chassiKeyReleased(evt);
            }
        });

        jlb_cor.setText("Cor:");

        jtf_placa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_placa.setEnabled(false);
        jtf_placa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_placaKeyReleased(evt);
            }
        });

        try {
            jft_cnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jft_cnpj.setEnabled(false);
        jft_cnpj.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jlb_cnpj.setText("CNPJ:");

        jlb_marca.setText("Marca:");

        jtf_marca.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_marca.setEnabled(false);
        jtf_marca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_marcaKeyReleased(evt);
            }
        });

        jlb_ano.setText("Ano:");

        try {
            jft_ano.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jft_ano.setEnabled(false);
        jft_ano.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jft_ano.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jft_anoKeyReleased(evt);
            }
        });

        jlb_quilometragem.setText("Quilometragem:");

        jtf_quilometragem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_quilometragem.setEnabled(false);
        jtf_quilometragem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_quilometragemKeyReleased(evt);
            }
        });

        jtf_modelo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_modelo.setEnabled(false);
        jtf_modelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_modeloKeyReleased(evt);
            }
        });

        jlb_modelo.setText("Modelo:");

        jlb_tipo.setText("Tipo:");

        jtf_tipo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_tipo.setEnabled(false);
        jtf_tipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_tipoKeyReleased(evt);
            }
        });

        jlb_alugados.setText("Veiculo alugado:");

        jrb_sim.setText("Sim");
        jrb_sim.setEnabled(false);
        jrb_sim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_simActionPerformed(evt);
            }
        });

        jrb_nao.setText("Não");
        jrb_nao.setEnabled(false);
        jrb_nao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_naoActionPerformed(evt);
            }
        });

        jtf_nomeEmpresa.setEditable(false);
        jtf_nomeEmpresa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_nomeEmpresa.setEnabled(false);
        jtf_nomeEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_nomeEmpresaActionPerformed(evt);
            }
        });

        jbn_buscar.setText("Buscar");
        jbn_buscar.setEnabled(false);
        jbn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_buscarActionPerformed(evt);
            }
        });

        jtf_cor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_cor.setEnabled(false);
        jtf_cor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_corKeyReleased(evt);
            }
        });

        jlb_chassi.setText("Chassi:");

        jtf_idCli.setEditable(false);
        jtf_idCli.setBackground(new java.awt.Color(204, 204, 204));
        jtf_idCli.setBorder(null);
        jtf_idCli.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jtf_idCli.setEnabled(false);
        jtf_idCli.setFocusable(false);
        jtf_idCli.setOpaque(false);
        jtf_idCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_idCliActionPerformed(evt);
            }
        });

        jtf_idAlug.setEditable(false);
        jtf_idAlug.setBorder(null);
        jtf_idAlug.setEnabled(false);
        jtf_idAlug.setFocusable(false);
        jtf_idAlug.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jlb_alugados)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jrb_sim)
                            .addGap(18, 18, 18)
                            .addComponent(jrb_nao)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                            .addComponent(jtf_idCli, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(75, 75, 75)
                            .addComponent(jtf_idAlug, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jtf_nomeEmpresa)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jlb_cnpj)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jft_cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbn_buscar)
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jlb_marca)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtf_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jlb_modelo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtf_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jlb_ano)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jft_ano, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(32, 32, 32)
                            .addComponent(jlb_tipo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtf_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jlb_placa)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jtf_placa, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(32, 32, 32)
                            .addComponent(jlb_cor)
                            .addGap(18, 18, 18)
                            .addComponent(jtf_cor, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jlb_quilometragem)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtf_quilometragem, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlb_chassi)
                            .addGap(32, 32, 32)
                            .addComponent(jtf_chassi, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(17, 17, 17))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jpl_opcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_alugados)
                    .addComponent(jrb_sim)
                    .addComponent(jrb_nao)
                    .addComponent(jtf_idCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_idAlug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jft_cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlb_cnpj)
                    .addComponent(jbn_buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_nomeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlb_placa)
                    .addComponent(jlb_cor)
                    .addComponent(jtf_cor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_marca)
                    .addComponent(jtf_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlb_modelo)
                    .addComponent(jtf_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_ano)
                    .addComponent(jft_ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlb_tipo)
                    .addComponent(jtf_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_quilometragem)
                    .addComponent(jtf_quilometragem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_chassi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlb_chassi))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpl_opcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbn_fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_fecharActionPerformed
       
        pneu.fechar();
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jbn_fecharActionPerformed

    private void jbn_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_limparActionPerformed
        limpar();
        // TODO add your handling code here:
    }//GEN-LAST:event_jbn_limparActionPerformed

    private void jbn_cadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_cadastroActionPerformed
        if(ifNull()){
            Veiculo v = new Veiculo();
        VeiculoDAO vd;

        if (jrb_sim.isSelected()) {
            v.setVeicAlugado("SIM");
        }
        if (jrb_nao.isSelected()) {
            v.setVeicAlugado("NAO");
        }
        try {
            vd = new VeiculoDAO();
            v.setChassi(jtf_chassi.getText());
            v.setPlaca(jtf_placa.getText());
            v.setModelo(jtf_modelo.getText());
            v.setMarca(jtf_marca.getText());
            v.setCor(jtf_cor.getText());
            v.setTipo(jtf_tipo.getText());
            v.setAno(Integer.parseInt(jft_ano.getText()));
            v.getVeicAlugado();
            v.setKm(Integer.parseInt(jtf_quilometragem.getText()));
            v.setIdCli(Integer.parseInt(jtf_idCli.getText()));
            vd.inserir(v);
            limpar();

            //readJTable();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(jif_cadastroVeiculo.class.getName()).log(Level.SEVERE, null, ex);
        }
        }else{
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos!!!" , "ATENÇÃO",JOptionPane.WARNING_MESSAGE);
        }
        

    }//GEN-LAST:event_jbn_cadastroActionPerformed

    private void jbn_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_novoActionPerformed
        jbn_cadastro.setEnabled(true);
        jbn_limpar.setEnabled(true);
        jtf_placa.setEnabled(true);
        jtf_chassi.setEnabled(true);
        jft_cnpj.setEnabled(true);
        jtf_marca.setEnabled(true);
        jft_ano.setEnabled(true);
        jtf_quilometragem.setEnabled(true);
        jtf_modelo.setEnabled(true);
        jtf_tipo.setEnabled(true);
        jrb_sim.setEnabled(true);
        jrb_nao.setEnabled(true);
        jbn_buscar.setEnabled(true);
        jbn_buscar.setEnabled(true);
        jtf_nomeEmpresa.setEnabled(true);
        jtf_cor.setEnabled(true);
        jbn_pneu.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jbn_novoActionPerformed

    private void jrb_simActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_simActionPerformed
        jrb_nao.setSelected(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jrb_simActionPerformed

    private void jrb_naoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_naoActionPerformed
        jrb_sim.setSelected(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jrb_naoActionPerformed

    private void jbn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_buscarActionPerformed
        Cliente c = new Cliente();
        ClienteDAO cd = new ClienteDAO();
        Aluguel al = new Aluguel();
        AluguelDAO aldao = new AluguelDAO();

        c.setCnpj(jft_cnpj.getText());
        al.setPlaca(jtf_placa.getText());
        int retorno = 0;
        int retorno1 = 0;
       // String retorno3 = "mano";
        try {
            Connection con = null;
            con = TesteBanco.getConnection();
            String sql = "SELECT marca, modelo, ano, placa, chassi, cor, km, tipo FROM Aluguel WHERE idAlug = ?";
            PreparedStatement stmt = null;
            ResultSet rs = null;
            
            retorno = cd.buscarCnpj(c.getCnpj());
            retorno1 = aldao.BuscarVeicAlugado(al.getPlaca());
            stmt = con.prepareStatement(sql);
            stmt.setInt(1, retorno1);
            rs = stmt.executeQuery();
            if (rs.next()) {

                jtf_chassi.setText(rs.getString("chassi"));
                jtf_placa.setText(rs.getString("placa"));
                jtf_modelo.setText(rs.getString("modelo"));
                jtf_marca.setText(rs.getString("marca"));
                jtf_cor.setText(rs.getString("cor"));
                jft_ano.setText(String.valueOf(rs.getInt("ano")));
                jtf_tipo.setText(rs.getString("tipo"));
                jtf_quilometragem.setText(String.valueOf(rs.getInt("km")));
            }

        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Erro no select completo de veiculo" + ex);
        }        johnson();

        jtf_idCli.setText(String.valueOf(retorno));
        jtf_idAlug.setText(String.valueOf(retorno1));
        

    }//GEN-LAST:event_jbn_buscarActionPerformed

    private void jtf_nomeEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_nomeEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_nomeEmpresaActionPerformed

    private void jtf_idCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_idCliActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_idCliActionPerformed

    private void jbn_pneuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_pneuActionPerformed
      
        
       // pneu.setPosicao();
    ((BasicInternalFrameUI)pneu.getUI()).setNorthPane(null);
    getParent().add(pneu);
    pneu.moveToFront();
    pneu.setLocation(400, 150);
    pneu.setVisible(true);
      
        
// TODO add your handling code here:
    }//GEN-LAST:event_jbn_pneuActionPerformed

    private void jtf_placaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_placaKeyReleased
        jtf_placa.setText(jtf_placa.getText().toUpperCase());
      
        if(validaT.validaTam(jtf_placa.getText(), 7)){
            String novo = validaT.diminui(jtf_placa.getText(), 7);
            jtf_placa.setText(novo);
            JOptionPane.showMessageDialog(null, "A quantidade de caracteres exede o limite permitido", "ATENÇÃO!!!", JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_placaKeyReleased

    private void jtf_corKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_corKeyReleased
        jtf_cor.setText(jtf_cor.getText().toUpperCase());
        if(validaT.validaTam(jtf_cor.getText(), 30)){
            String novo = validaT.diminui(jtf_cor.getText(), 30);
            jtf_cor.setText(novo);
            JOptionPane.showMessageDialog(null, "A quantidade de caracteres exede o limite permitido", "ATENÇÃO!!!", JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jtf_corKeyReleased

    private void jtf_marcaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_marcaKeyReleased
        jtf_marca.setText(jtf_marca.getText().toUpperCase());
        
        
         if(validaT.validaTam(jtf_marca.getText(), 30)){
            String novo = validaT.diminui(jtf_marca.getText(), 30);
            jtf_marca.setText(novo);
            JOptionPane.showMessageDialog(null, "A quantidade de caracteres exede o limite permitido", "ATENÇÃO!!!", JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_marcaKeyReleased

    private void jtf_modeloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_modeloKeyReleased
        jtf_modelo.setText(jtf_modelo.getText().toUpperCase());
        if(validaT.validaTam(jtf_modelo.getText(), 30)){
            String novo = validaT.diminui(jtf_modelo.getText(), 30);
            jtf_modelo.setText(novo);
            JOptionPane.showMessageDialog(null, "A quantidade de caracteres exede o limite permitido", "ATENÇÃO!!!", JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_modeloKeyReleased

    private void jtf_tipoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_tipoKeyReleased
        jtf_tipo.setText(jtf_tipo.getText().toUpperCase());
        if(validaT.validaTam(jtf_tipo.getText(), 30)){
            String novo = validaT.diminui(jtf_tipo.getText(), 30);
            jtf_tipo.setText(novo);
            JOptionPane.showMessageDialog(null, "A quantidade de caracteres exede o limite permitido", "ATENÇÃO!!!", JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_tipoKeyReleased

    private void jtf_chassiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_chassiKeyReleased
        jtf_chassi.setText(jtf_chassi.getText().toUpperCase());
        if(validaT.validaTam(jtf_chassi.getText(), 17)){
            String novo = validaT.diminui(jtf_chassi.getText(), 17);
            jtf_chassi.setText(novo);
            JOptionPane.showMessageDialog(null, "A quantidade de caracteres exede o limite permitido", "ATENÇÃO!!!", JOptionPane.WARNING_MESSAGE);
        }
            // TODO add your handling code here:
    }//GEN-LAST:event_jtf_chassiKeyReleased

    private void jft_anoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jft_anoKeyReleased
        // TODO add your handling code here:
        jft_ano.setText(jft_ano.getText().toUpperCase());
        if(validaT.validaTam(jft_ano.getText(), 4)){
            String novo = validaT.diminui(jft_ano.getText(), 4);
            jft_ano.setText(novo);
            JOptionPane.showMessageDialog(null, "A quantidade de caracteres exede o limite permitido", "ATENÇÃO!!!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jft_anoKeyReleased

    private void jtf_quilometragemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_quilometragemKeyReleased
        // TODO add your handling code here:
        jtf_quilometragem.setText(jtf_quilometragem.getText().toUpperCase());
        if(validaT.validaTam(jtf_quilometragem.getText(), 7)){
            String novo = validaT.diminui(jtf_quilometragem.getText(), 7);
            jtf_quilometragem.setText(novo);
            JOptionPane.showMessageDialog(null, "A quantidade de caracteres exede o limite permitido", "ATENÇÃO!!!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jtf_quilometragemKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton jbn_buscar;
    private javax.swing.JButton jbn_cadastro;
    private javax.swing.JButton jbn_fechar;
    private javax.swing.JButton jbn_limpar;
    private javax.swing.JButton jbn_novo;
    private javax.swing.JButton jbn_pneu;
    private javax.swing.JFormattedTextField jft_ano;
    private javax.swing.JFormattedTextField jft_cnpj;
    private javax.swing.JLabel jlb_alugados;
    private javax.swing.JLabel jlb_ano;
    private javax.swing.JLabel jlb_chassi;
    private javax.swing.JLabel jlb_cnpj;
    private javax.swing.JLabel jlb_cor;
    private javax.swing.JLabel jlb_marca;
    private javax.swing.JLabel jlb_modelo;
    private javax.swing.JLabel jlb_placa;
    private javax.swing.JLabel jlb_quilometragem;
    private javax.swing.JLabel jlb_tipo;
    private javax.swing.JPanel jpl_opcoes;
    private javax.swing.JRadioButton jrb_nao;
    private javax.swing.JRadioButton jrb_sim;
    private javax.swing.JTextField jtf_chassi;
    private javax.swing.JTextField jtf_cor;
    private javax.swing.JTextField jtf_idAlug;
    private javax.swing.JTextField jtf_idCli;
    private javax.swing.JTextField jtf_marca;
    private javax.swing.JTextField jtf_modelo;
    private javax.swing.JTextField jtf_nomeEmpresa;
    private javax.swing.JTextField jtf_placa;
    private javax.swing.JTextField jtf_quilometragem;
    private javax.swing.JTextField jtf_tipo;
    // End of variables declaration//GEN-END:variables
}
