package view;

import java.awt.Dimension;
import javax.swing.JOptionPane;
import model.bean.Motorista;
import model.bean.validaCPF;
import model.dao.MotoristaDAO;
import Utilitarios.WebServiceCep;
import connection.TesteBanco;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.bean.Validadores;
import model.bean.Veiculo;
import model.dao.VeiculoDAO;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author total
 */
public class jif_cadastroMotorista extends javax.swing.JInternalFrame {

    /**
     * Creates new form jif_cadastroMotorista
     */
    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }
    validaCPF valida = new validaCPF();

    public boolean ifNull(){
        if(jtf_endRua.getText().equals("")){
            return false;
        }
        if(jft_endCEP.getText().equals("")){
            return false;
        }
        
        if(jtf_endBairro.getText().equals("")){
            return false;
        }
        
        if(jtf_endUF.getText().equals("")){
            return false;
        }
        if(jtf_endCidade.getText().equals("")){
            return false;
        }
        if(jtf_endNum.getText().equals("")){
            return false;
        }
        if(jtf_carroModel.getText().equals("")){
            return false;
        }
        if(jtf_motoSobrenome.getText().equals("")){
            return false;
        }
        if( jft_motoCPF.getText().equals("   .   .   -  ")){
            return false;
        }
        if(jft_motoRG.getText().equals("  .   .   - ")){
            return false;
        }
        if ("(  )      -    ".equals(jft_cel.getText()) && "(  )     -    ".equals(jft_tel.getText()) ){
            
            return false;
        }
        if(jtf_CNH.getText().equals("")){
            return false;
        }
        
        if(jft_validadeCNH.getText().equals("  /  /    ")){
            return false;
        }
        if(jrb_fem.isSelected() == false && jrb_masc.isSelected() == false){
            return false;
        }
        
        return true;
    }
    public void ChamaModelo(){
        Veiculo v = new Veiculo();
        v.setPlaca(jtf_placa.getText());
        String retorno2 = "";
        try {
            VeiculoDAO vd = new VeiculoDAO();
            
            retorno2 = vd.BuscarVeic2(v.getPlaca());
            
            
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(jif_cadastroVeiculo.class.getName()).log(Level.SEVERE, null, ex);
        }
        //jtf_idPlaca.setText(String.valueOf(retorno));
        
        jtf_carroModel.setText(retorno2);
    }
    
    public void limpar() {
        jtf_carroModel.setText("");
        jtf_motoNome.setText("");
        jtf_placa.setText("");
        jtf_motoSobrenome.setText("");
        jft_motoCPF.setText("");
        jft_motoRG.setText("");
        jft_tel.setText("");
        jft_cel.setText("");
        jtf_CNH.setText("");
        jft_validadeCNH.setText("");
        jrb_masc.setSelected(false);
        jrb_fem.setSelected(false);
        jtf_endRua.setText("");
        jft_endCEP.setText("");
        jtf_endBairro.setText("");
        jtf_endNum.setText("");
        jtf_endBairro.setText("");
        jtf_endUF.setText("");
        jtf_endCidade.setText("");
    }

    public jif_cadastroMotorista() {

        initComponents();
        jtf_idPlaca.setVisible(false);
    }
        Validadores validaT = new Validadores();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpl_opcoes = new javax.swing.JPanel();
        jbn_fechar = new javax.swing.JButton();
        jbn_limpar = new javax.swing.JButton();
        jbn_cadastro = new javax.swing.JButton();
        jbn_novo = new javax.swing.JButton();
        jlb_nome = new javax.swing.JLabel();
        jtf_motoSobrenome = new javax.swing.JTextField();
        jlb_sobrenome = new javax.swing.JLabel();
        jtf_carroModel = new javax.swing.JTextField();
        jlb_rg = new javax.swing.JLabel();
        jft_motoRG = new javax.swing.JFormattedTextField();
        jft_motoCPF = new javax.swing.JFormattedTextField();
        jlb_cpf = new javax.swing.JLabel();
        jlb_celular = new javax.swing.JLabel();
        jft_cel = new javax.swing.JFormattedTextField();
        jlb_telefone = new javax.swing.JLabel();
        jft_tel = new javax.swing.JFormattedTextField();
        jlb_cnh = new javax.swing.JLabel();
        jlb_cnhValidade = new javax.swing.JLabel();
        jft_validadeCNH = new javax.swing.JFormattedTextField();
        jlb_rua = new javax.swing.JLabel();
        jtf_endRua = new javax.swing.JTextField();
        jlb_numero = new javax.swing.JLabel();
        jtf_endNum = new javax.swing.JTextField();
        jlb_cep = new javax.swing.JLabel();
        jft_endCEP = new javax.swing.JFormattedTextField();
        jlb_bairro = new javax.swing.JLabel();
        jtf_endBairro = new javax.swing.JTextField();
        jtf_endCidade = new javax.swing.JTextField();
        jlb_cidade = new javax.swing.JLabel();
        jlb_uf = new javax.swing.JLabel();
        jcb_cnhCategoria = new javax.swing.JComboBox();
        jlb_cnhCategoria = new javax.swing.JLabel();
        jtf_endUF = new javax.swing.JTextField();
        jtf_placa = new javax.swing.JTextField();
        jbn_buscarPlaca = new javax.swing.JButton();
        jtf_idPlaca = new javax.swing.JTextField();
        jtf_CNH = new javax.swing.JTextField();
        jtf_motoNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jrb_masc = new javax.swing.JRadioButton();
        jrb_fem = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        setForeground(java.awt.Color.white);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro Motorista"));

        jpl_opcoes.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jpl_opcoes.setToolTipText("Opções");

        jbn_fechar.setText("Fechar");
        jbn_fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_fecharActionPerformed(evt);
            }
        });

        jbn_limpar.setText("Limpar");
        jbn_limpar.setEnabled(false);
        jbn_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_limparActionPerformed(evt);
            }
        });

        jbn_cadastro.setText("Cadastrar");
        jbn_cadastro.setEnabled(false);
        jbn_cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_cadastroActionPerformed(evt);
            }
        });

        jbn_novo.setText("Novo");
        jbn_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_novoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpl_opcoesLayout = new javax.swing.GroupLayout(jpl_opcoes);
        jpl_opcoes.setLayout(jpl_opcoesLayout);
        jpl_opcoesLayout.setHorizontalGroup(
            jpl_opcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpl_opcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpl_opcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbn_fechar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbn_limpar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbn_novo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbn_cadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpl_opcoesLayout.setVerticalGroup(
            jpl_opcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpl_opcoesLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jbn_novo)
                .addGap(27, 27, 27)
                .addComponent(jbn_cadastro)
                .addGap(18, 18, 18)
                .addComponent(jbn_limpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(jbn_fechar)
                .addContainerGap())
        );

        jlb_nome.setText("Nome:");

        jtf_motoSobrenome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_motoSobrenome.setEnabled(false);
        jtf_motoSobrenome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_motoSobrenomeKeyReleased(evt);
            }
        });

        jlb_sobrenome.setText("Sobrenome:");

        jtf_carroModel.setEditable(false);
        jtf_carroModel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_carroModel.setEnabled(false);

        jlb_rg.setText("RG:");

        try {
            jft_motoRG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jft_motoRG.setEnabled(false);
        jft_motoRG.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        try {
            jft_motoCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jft_motoCPF.setEnabled(false);
        jft_motoCPF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jft_motoCPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jft_motoCPFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jft_motoCPFFocusLost(evt);
            }
        });

        jlb_cpf.setText("CPF:");

        jlb_celular.setText("Celular:");

        try {
            jft_cel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jft_cel.setEnabled(false);
        jft_cel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jlb_telefone.setText("Telefone Residencial:");

        try {
            jft_tel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jft_tel.setEnabled(false);
        jft_tel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jlb_cnh.setText("CNH:");

        jlb_cnhValidade.setText("Validade:");

        try {
            jft_validadeCNH.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jft_validadeCNH.setEnabled(false);
        jft_validadeCNH.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jlb_rua.setText("Rua:");

        jtf_endRua.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_endRua.setEnabled(false);
        jtf_endRua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_endRuaKeyReleased(evt);
            }
        });

        jlb_numero.setText("Nº:");

        jtf_endNum.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_endNum.setEnabled(false);
        jtf_endNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_endNumKeyReleased(evt);
            }
        });

        jlb_cep.setText("CEP:");

        try {
            jft_endCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jft_endCEP.setEnabled(false);
        jft_endCEP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jft_endCEP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jft_endCEPKeyReleased(evt);
            }
        });

        jlb_bairro.setText("Bairro:");

        jtf_endBairro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_endBairro.setEnabled(false);
        jtf_endBairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_endBairroKeyReleased(evt);
            }
        });

        jtf_endCidade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_endCidade.setEnabled(false);
        jtf_endCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_endCidadeKeyReleased(evt);
            }
        });

        jlb_cidade.setText("Cidade:");

        jlb_uf.setText("UF:");

        jcb_cnhCategoria.setEditable(true);
        jcb_cnhCategoria.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jcb_cnhCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C", "D" }));
        jcb_cnhCategoria.setEnabled(false);

        jlb_cnhCategoria.setText("Categoria:");

        jtf_endUF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_endUF.setEnabled(false);
        jtf_endUF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_endUFKeyReleased(evt);
            }
        });

        jtf_placa.setEnabled(false);
        jtf_placa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_placaKeyReleased(evt);
            }
        });

        jbn_buscarPlaca.setText("Buscar");
        jbn_buscarPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_buscarPlacaActionPerformed(evt);
            }
        });

        jtf_idPlaca.setEditable(false);
        jtf_idPlaca.setBorder(null);
        jtf_idPlaca.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jtf_idPlaca.setEnabled(false);
        jtf_idPlaca.setFocusable(false);

        jtf_CNH.setEnabled(false);
        jtf_CNH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_CNHKeyReleased(evt);
            }
        });

        jtf_motoNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_motoNome.setEnabled(false);
        jtf_motoNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_motoNomeKeyReleased(evt);
            }
        });

        jLabel1.setText("Sexo:");

        jrb_masc.setText("Masculino");
        jrb_masc.setEnabled(false);
        jrb_masc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_mascActionPerformed(evt);
            }
        });

        jrb_fem.setText("Feminino");
        jrb_fem.setEnabled(false);
        jrb_fem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_femActionPerformed(evt);
            }
        });

        jLabel2.setText("Placa:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtf_placa, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbn_buscarPlaca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtf_carroModel, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlb_sobrenome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_motoSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_idPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlb_rg)
                                .addGap(3, 3, 3)
                                .addComponent(jft_motoRG, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlb_cpf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jft_motoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlb_celular)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jft_cel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jlb_telefone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jft_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlb_nome)
                                .addGap(20, 20, 20)
                                .addComponent(jtf_motoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlb_cnh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_CNH, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jlb_cnhCategoria)
                                .addGap(18, 18, 18)
                                .addComponent(jcb_cnhCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jlb_cnhValidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jft_validadeCNH, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jrb_masc)
                                .addGap(18, 18, 18)
                                .addComponent(jrb_fem))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jlb_cep)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jft_endCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(jlb_uf)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtf_endUF, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jlb_cidade)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtf_endCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(72, 72, 72))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(jpl_opcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlb_numero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtf_endNum, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlb_bairro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_endBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlb_rua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_endRua, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlb_nome)
                            .addComponent(jtf_motoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtf_motoSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlb_sobrenome)
                            .addComponent(jtf_idPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlb_rg)
                            .addComponent(jft_motoRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jft_motoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlb_cpf))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jrb_masc)
                            .addComponent(jrb_fem))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jft_cel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlb_celular)
                            .addComponent(jft_tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlb_telefone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtf_placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbn_buscarPlaca)
                            .addComponent(jtf_carroModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlb_cnh)
                            .addComponent(jft_validadeCNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlb_cnhValidade)
                            .addComponent(jlb_cnhCategoria)
                            .addComponent(jcb_cnhCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_CNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlb_cep)
                            .addComponent(jft_endCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlb_uf)
                            .addComponent(jtf_endUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlb_cidade)
                            .addComponent(jtf_endCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jpl_opcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_endRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlb_rua))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_numero)
                    .addComponent(jtf_endNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlb_bairro)
                    .addComponent(jtf_endBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbn_fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_fecharActionPerformed

        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jbn_fecharActionPerformed

    private void jbn_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_limparActionPerformed
        limpar();
        // TODO add your handling code here:
    }//GEN-LAST:event_jbn_limparActionPerformed

    private void jbn_cadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_cadastroActionPerformed

        boolean teste = ifNull();
        if(teste){
            Motorista m = new Motorista();
        MotoristaDAO md = new MotoristaDAO();
        if (jrb_fem.isSelected()) {
            m.setSexo("Feminino");
        }
        if (jrb_masc.isSelected()) {
           m.setSexo("Masculino");
        }
        
        m.setNome(jtf_motoNome.getText().toUpperCase());
        m.setSobrenome(jtf_motoSobrenome.getText().toUpperCase());
        m.setCpf(jft_motoCPF.getText());
        m.setRg(jft_motoRG.getText());
        m.setTelefone(jft_tel.getText().toUpperCase());
        m.setCelular(jft_cel.getText().toUpperCase());
        m.setRegistro(jtf_CNH.getText());
        m.setValidade(jft_validadeCNH.getText());
        m.setCategoria(String.valueOf(jcb_cnhCategoria.getSelectedItem()));
        m.setRua(jtf_endRua.getText().toUpperCase());
        m.setCep(jft_endCEP.getText());
        m.setBairro(jtf_endBairro.getText().toUpperCase());
        m.setNumero(Integer.parseInt(jtf_endNum.getText()));
        m.setTelefone(jft_tel.getText().toUpperCase());
        m.setCidade(jtf_endCidade.getText().toUpperCase());
        m.setUf(jtf_endUF.getText().toUpperCase());
        m.setId_veiculo(Integer.parseInt(jtf_idPlaca.getText()));
        m.getSexo();
        md.inserir(m);
        limpar();
        }else{
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos!!!" , "ATENÇÃO",JOptionPane.WARNING_MESSAGE);
        }
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jbn_cadastroActionPerformed

    private void jbn_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_novoActionPerformed
        jbn_cadastro.setEnabled(true);
        jbn_limpar.setEnabled(true);
        jtf_carroModel.setEnabled(true);
        jtf_motoNome.setEnabled(true);
        jtf_motoSobrenome.setEnabled(true);
        jft_motoCPF.setEnabled(true);
        jft_motoRG.setEnabled(true);
        jft_tel.setEnabled(true);
        jft_cel.setEnabled(true);
        jtf_CNH.setEnabled(true);
        jft_validadeCNH.setEnabled(true);
        jcb_cnhCategoria.setEnabled(true);
        jtf_endRua.setEnabled(true);
        jft_endCEP.setEnabled(true);
        jtf_endBairro.setEnabled(true);
        jtf_endNum.setEnabled(true);
        jft_tel.setEnabled(true);
        jtf_endCidade.setEnabled(true);
        jtf_endUF.setEnabled(true);
        jtf_placa.setEnabled(true);
        jrb_masc.setEnabled(true);
        jrb_fem.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jbn_novoActionPerformed

    private void jft_motoCPFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jft_motoCPFFocusLost

        String cpf = new String(jft_motoCPF.getText());

        int g = valida.ValidaCpf(cpf);

        if (g == 0) {

        } else {
            JOptionPane.showMessageDialog(null, "CPF invalido");
            jft_motoCPF.setText("");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jft_motoCPFFocusLost

    private void jft_motoCPFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jft_motoCPFFocusGained
        // jft_motoCPF.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jft_motoCPFFocusGained

    private void jft_endCEPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jft_endCEPKeyReleased
        String cp = jft_endCEP.getText();
        cp = cp.replaceAll("\\D*", ""); //ignora qualquer coisa que não seja numero.  
        int cont = cp.length();

        if (cont == 8) {
            try {
                correio();
            } catch (Error e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jft_endCEPKeyReleased

    private void jbn_buscarPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_buscarPlacaActionPerformed
        Veiculo v = new Veiculo();
        v.setPlaca(jtf_placa.getText());

        int retorno = 0;
        try {
            VeiculoDAO vd = new VeiculoDAO();
            retorno = vd.BuscarVeicAlugado(v.getPlaca());
            if(retorno == 0){
                JOptionPane.showMessageDialog(null, "Placa incorreta!!!" , "ATENÇÃO!!!", JOptionPane.WARNING_MESSAGE);
            }
            
                
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(jif_cadastroVeiculo.class.getName()).log(Level.SEVERE, null, ex);
        }
        jtf_idPlaca.setText(String.valueOf(retorno));
        System.out.println("pega -> " + retorno);
        ChamaModelo();
        // TODO add your handling code here:
    }//GEN-LAST:event_jbn_buscarPlacaActionPerformed

    private void jrb_mascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_mascActionPerformed
        jrb_fem.setSelected(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jrb_mascActionPerformed

    private void jrb_femActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_femActionPerformed
        jrb_masc.setSelected(false);
        // TODO add yjrb_mascour handling code here:
    }//GEN-LAST:event_jrb_femActionPerformed

    private void jtf_motoNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_motoNomeKeyReleased
         
        jtf_motoNome.setText(jtf_motoNome.getText().toUpperCase());
        
         if(validaT.validaTam(jtf_motoNome.getText(), 100)){
            String novo = validaT.diminui(jtf_motoNome.getText(), 100);
            jtf_motoNome.setText(novo);
            JOptionPane.showMessageDialog(null, "A quantidade de caracteres exede o limite permitido", "ATENÇÃO!!!", JOptionPane.WARNING_MESSAGE);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jtf_motoNomeKeyReleased

    private void jtf_motoSobrenomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_motoSobrenomeKeyReleased
         jtf_motoSobrenome.setText(jtf_motoSobrenome.getText().toUpperCase());
         if(validaT.validaTam(jtf_motoSobrenome.getText(), 100)){
            String novo = validaT.diminui(jtf_motoSobrenome.getText(), 100);
            jtf_motoSobrenome.setText(novo);
            JOptionPane.showMessageDialog(null, "A quantidade de caracteres exede o limite permitido", "ATENÇÃO!!!", JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_motoSobrenomeKeyReleased

    private void jtf_placaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_placaKeyReleased
        jtf_placa.setText(jtf_placa.getText().toUpperCase());
         if(validaT.validaTam(jtf_placa.getText(), 100)){
            String novo = validaT.diminui(jtf_placa.getText(), 100);
            jtf_placa.setText(novo);
            JOptionPane.showMessageDialog(null, "A quantidade de caracteres exede o limite permitido", "ATENÇÃO!!!", JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_placaKeyReleased

    private void jtf_endUFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_endUFKeyReleased
        // TODO add your handling code here:
         jtf_endUF.setText(jtf_endUF.getText().toUpperCase());
     if(validaT.validaTam(jtf_endUF.getText(), 2)){
            String novo = validaT.diminui(jtf_endUF.getText(), 2);
            jtf_endUF.setText(novo);
            JOptionPane.showMessageDialog(null, "A quantidade de caracteres exede o limite permitido", "ATENÇÃO!!!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jtf_endUFKeyReleased

    private void jtf_endCidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_endCidadeKeyReleased
        // TODO add your handling code here:
        jtf_endCidade.setText(jtf_endCidade.getText().toUpperCase());
        if(validaT.validaTam(jtf_endCidade.getText(), 100)){
            String novo = validaT.diminui(jtf_endCidade.getText(), 100);
            jtf_endCidade.setText(novo);
            JOptionPane.showMessageDialog(null, "A quantidade de caracteres exede o limite permitido", "ATENÇÃO!!!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jtf_endCidadeKeyReleased

    private void jtf_endRuaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_endRuaKeyReleased
        jtf_endRua.setText(jtf_endRua.getText().toUpperCase());
         if(validaT.validaTam(jtf_endRua.getText(), 100)){
            String novo = validaT.diminui(jtf_endRua.getText(), 100);
            jtf_endRua.setText(novo);
            JOptionPane.showMessageDialog(null, "A quantidade de caracteres exede o limite permitido", "ATENÇÃO!!!", JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_endRuaKeyReleased

    private void jtf_endBairroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_endBairroKeyReleased
        jtf_endBairro.setText(jtf_endBairro.getText().toUpperCase());
         if(validaT.validaTam(jtf_endBairro.getText(), 100)){
            String novo = validaT.diminui(jtf_endBairro.getText(), 100);
            jtf_endBairro.setText(novo);
            JOptionPane.showMessageDialog(null, "A quantidade de caracteres exede o limite permitido", "ATENÇÃO!!!", JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_endBairroKeyReleased

    private void jtf_endNumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_endNumKeyReleased
        // TODO add your handling code here:
        jtf_endNum.setText(jtf_endNum.getText().toUpperCase());
     if(validaT.validaTam(jtf_endNum.getText(), 10)){
            String novo = validaT.diminui(jtf_endNum.getText(), 10);
            jtf_endNum.setText(novo);
            JOptionPane.showMessageDialog(null, "A quantidade de caracteres exede o limite permitido", "ATENÇÃO!!!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jtf_endNumKeyReleased

    private void jtf_CNHKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_CNHKeyReleased
        jtf_CNH.setText(jtf_CNH.getText().toUpperCase());
     if(validaT.validaTam(jtf_CNH.getText(), 15)){
            String novo = validaT.diminui(jtf_CNH.getText(), 15);
            jtf_CNH.setText(novo);
            JOptionPane.showMessageDialog(null, "A quantidade de caracteres exede o limite permitido", "ATENÇÃO!!!", JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_CNHKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbn_buscarPlaca;
    private javax.swing.JButton jbn_cadastro;
    private javax.swing.JButton jbn_fechar;
    private javax.swing.JButton jbn_limpar;
    private javax.swing.JButton jbn_novo;
    private javax.swing.JComboBox jcb_cnhCategoria;
    private javax.swing.JFormattedTextField jft_cel;
    private javax.swing.JFormattedTextField jft_endCEP;
    private javax.swing.JFormattedTextField jft_motoCPF;
    private javax.swing.JFormattedTextField jft_motoRG;
    private javax.swing.JFormattedTextField jft_tel;
    private javax.swing.JFormattedTextField jft_validadeCNH;
    private javax.swing.JLabel jlb_bairro;
    private javax.swing.JLabel jlb_celular;
    private javax.swing.JLabel jlb_cep;
    private javax.swing.JLabel jlb_cidade;
    private javax.swing.JLabel jlb_cnh;
    private javax.swing.JLabel jlb_cnhCategoria;
    private javax.swing.JLabel jlb_cnhValidade;
    private javax.swing.JLabel jlb_cpf;
    private javax.swing.JLabel jlb_nome;
    private javax.swing.JLabel jlb_numero;
    private javax.swing.JLabel jlb_rg;
    private javax.swing.JLabel jlb_rua;
    private javax.swing.JLabel jlb_sobrenome;
    private javax.swing.JLabel jlb_telefone;
    private javax.swing.JLabel jlb_uf;
    private javax.swing.JPanel jpl_opcoes;
    private javax.swing.JRadioButton jrb_fem;
    private javax.swing.JRadioButton jrb_masc;
    private javax.swing.JTextField jtf_CNH;
    private javax.swing.JTextField jtf_carroModel;
    private javax.swing.JTextField jtf_endBairro;
    private javax.swing.JTextField jtf_endCidade;
    private javax.swing.JTextField jtf_endNum;
    private javax.swing.JTextField jtf_endRua;
    private javax.swing.JTextField jtf_endUF;
    private javax.swing.JTextField jtf_idPlaca;
    private javax.swing.JTextField jtf_motoNome;
    private javax.swing.JTextField jtf_motoSobrenome;
    private javax.swing.JTextField jtf_placa;
    // End of variables declaration//GEN-END:variables
public void correio() {

        String cep = jft_endCEP.getText();

        WebServiceCep webServiceCep = WebServiceCep.searchCep(cep);

        if (webServiceCep.wasSuccessful()) {

            jtf_endRua.setText(webServiceCep.getLogradouroFull().toUpperCase());
            jtf_endBairro.setText(webServiceCep.getBairro().toUpperCase());
            jtf_endCidade.setText(webServiceCep.getCidade().toUpperCase());
            jtf_endUF.setText(webServiceCep.getUf().toUpperCase());

        } else {
            JOptionPane.showMessageDialog(null, webServiceCep.getResultText());

        }

    }

}
