/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Dimension;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.bean.Abastecimento;
import model.bean.Multa;
import model.bean.Veiculo;
import model.bean.validaCNPJ;
import model.dao.AbastecimentoDAO;
import model.dao.MultaDAO;
import model.dao.VeiculoDAO;

/**
 *
 * @author total
 */
public class jif_abastecimento extends javax.swing.JInternalFrame {

    /**
     * Creates new form jif_manutencao
     */
    public boolean verifica() {
        if (jtf_posto.getText().equals("")) {
            return false;

        }

        if (jtf_km.getText().equals("")) {
            return false;
        }
        if (jft_data.getText().equals("  /  /    ")) {
            return false;
        }
        if (jft_cnpj.getText().equals("  .   .   /    -  ")) {
            return false;
        }
        if (jft_valor.getText().equals("")) {
            return false;
        } else {
            return true;
        }
    }

    public void limpar() {
        jtf_posto.setText("");
        jtf_km.setText("");
        jft_valor.setText("");
        jtf_cupomFiscal.setText("");
        jtf_combustivel.setText("");
        jtf_litros.setText("");
        jft_data.setText("");
        jft_contato.setText("");
        jft_cnpj.setText("");
        jtf_modelo.setText("");

    }

    public void novo(boolean op) {
        jtf_posto.setEnabled(op);
        jtf_km.setEnabled(op);
        jft_valor.setEnabled(op);
        jtf_cupomFiscal.setEnabled(op);
        jtf_combustivel.setEnabled(op);
        jtf_litros.setEnabled(op);
        jft_data.setEnabled(op);
        jft_contato.setEnabled(op);
        jft_cnpj.setEnabled(op);
        jft_valor.setEnabled(op);
        jbn_cadastro.setEnabled(op);
        jbn_limpar.setEnabled(op);
    }

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    public jif_abastecimento() {
        initComponents();
        jtf_idveic.setVisible(false);
    }
    public void ChamaModelo() {
        Veiculo v = new Veiculo();
        v.setPlaca(jtf_placa.getText());
        String retorno2 = "";
        try {
            VeiculoDAO vd = new VeiculoDAO();

            retorno2 = vd.BuscarVeic2(v.getPlaca());

        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(jif_cadastroVeiculo.class.getName()).log(Level.SEVERE, null, ex);
        }

        jtf_modelo.setText(retorno2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpl_opcoes3 = new javax.swing.JPanel();
        jbn_fechar3 = new javax.swing.JButton();
        jbn_limpar = new javax.swing.JButton();
        jbn_cadastro = new javax.swing.JButton();
        jbn_novo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtf_placa = new javax.swing.JTextField();
        jbn_buscar = new javax.swing.JButton();
        jtf_modelo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtf_km = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jft_data = new javax.swing.JFormattedTextField();
        jtf_posto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jft_valor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jft_contato = new javax.swing.JFormattedTextField();
        jtf_cupomFiscal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtf_combustivel = new javax.swing.JTextField();
        jtf_litros = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jft_cnpj = new javax.swing.JFormattedTextField();
        jtf_idveic = new javax.swing.JTextField();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Abastecimento"));

        jpl_opcoes3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jpl_opcoes3.setToolTipText("Opções");

        jbn_fechar3.setText("Fechar");
        jbn_fechar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_fechar3ActionPerformed(evt);
            }
        });

        jbn_limpar.setText("Limpar");
        jbn_limpar.setEnabled(false);
        jbn_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_limparActionPerformed(evt);
            }
        });

        jbn_cadastro.setText("Cadastrar");
        jbn_cadastro.setEnabled(false);
        jbn_cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_cadastroActionPerformed(evt);
            }
        });

        jbn_novo.setText("Novo");
        jbn_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_novoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpl_opcoes3Layout = new javax.swing.GroupLayout(jpl_opcoes3);
        jpl_opcoes3.setLayout(jpl_opcoes3Layout);
        jpl_opcoes3Layout.setHorizontalGroup(
            jpl_opcoes3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpl_opcoes3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpl_opcoes3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbn_fechar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbn_limpar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbn_novo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbn_cadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpl_opcoes3Layout.setVerticalGroup(
            jpl_opcoes3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpl_opcoes3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jbn_novo)
                .addGap(27, 27, 27)
                .addComponent(jbn_cadastro)
                .addGap(18, 18, 18)
                .addComponent(jbn_limpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(jbn_fechar3)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Veiculo"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Placa:");

        jtf_placa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_placa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_placaKeyReleased(evt);
            }
        });

        jbn_buscar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbn_buscar.setText("Buscar");
        jbn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_buscarActionPerformed(evt);
            }
        });

        jtf_modelo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_modelo.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_placa, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbn_buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtf_modelo)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jbn_buscar)
                    .addComponent(jtf_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Km:");

        jtf_km.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_km.setEnabled(false);
        jtf_km.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_kmKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Valor total:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Cupom fiscal:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Data:");

        try {
            jft_data.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jft_data.setEnabled(false);
        jft_data.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jtf_posto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_posto.setEnabled(false);
        jtf_posto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_postoKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Posto:");

        jft_valor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jft_valor.setEnabled(false);
        jft_valor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jft_valorKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Contato:");

        try {
            jft_contato.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jft_contato.setEnabled(false);
        jft_contato.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jtf_cupomFiscal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_cupomFiscal.setEnabled(false);
        jtf_cupomFiscal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_cupomFiscalKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Combustivel");

        jtf_combustivel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_combustivel.setEnabled(false);
        jtf_combustivel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_combustivelKeyReleased(evt);
            }
        });

        jtf_litros.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_litros.setEnabled(false);
        jtf_litros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_litrosKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Litros:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Cnpj:");

        try {
            jft_cnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jft_cnpj.setEnabled(false);
        jft_cnpj.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jft_cnpj.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jft_cnpjFocusLost(evt);
            }
        });
        jft_cnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jft_cnpjActionPerformed(evt);
            }
        });
        jft_cnpj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jft_cnpjKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_posto, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtf_km, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(60, 60, 60)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jft_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtf_litros, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jft_data, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jtf_cupomFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jtf_combustivel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jtf_idveic, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel8))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jft_contato, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel11)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jft_cnpj))))))
                        .addGap(0, 18, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpl_opcoes3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpl_opcoes3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_posto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_km, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jft_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtf_cupomFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jtf_combustivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jft_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jtf_litros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jft_cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jft_contato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtf_idveic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbn_fechar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_fechar3ActionPerformed

        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jbn_fechar3ActionPerformed

    private void jbn_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_limparActionPerformed
        limpar();
        // TODO add your handling code here:Su
    }//GEN-LAST:event_jbn_limparActionPerformed

    private void jbn_cadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_cadastroActionPerformed
        Abastecimento a = new Abastecimento();
        AbastecimentoDAO ad;
        try {
            ad = new AbastecimentoDAO();
            a.setCnpj(jft_cnpj.getText());
            a.setCombustivel(jtf_combustivel.getText());
            a.setCupomFiscal(jtf_cupomFiscal.getText());
            a.setDataAbastecimento(jft_data.getText());
            a.setIdVeic(Integer.parseInt(jtf_idveic.getText()));
            a.setKm(Integer.parseInt(jtf_km.getText()));
            a.setLitros(Integer.parseInt(jtf_litros.getText()));
            a.setNomePosto(jtf_posto.getText());
            a.setValorTotal(Float.parseFloat(jft_valor.getText()));

            ad.inserir(a);
            limpar();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(jif_abastecimento.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jbn_cadastroActionPerformed

    private void jbn_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_novoActionPerformed

        novo(false);
        jtf_placa.setText("");
        jtf_placa.setEditable(true);
        jbn_buscar.setEnabled(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jbn_novoActionPerformed

    private void jbn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_buscarActionPerformed

        Veiculo v = new Veiculo();
        v.setPlaca(jtf_placa.getText());

        int retorno = 0;

        try {
            VeiculoDAO vd = new VeiculoDAO();
            retorno = vd.BuscarVeicAlugado(v.getPlaca());
            if(retorno > 0){
                novo(true);
            jtf_placa.setEditable(false);
            jbn_buscar.setEnabled(false);
            }else{
                JOptionPane.showMessageDialog(null, "Placa incorreta!!!" , "ATENÇÃO!!!", JOptionPane.WARNING_MESSAGE);
            }

        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(jif_cadastroVeiculo.class.getName()).log(Level.SEVERE, null, ex);
        }
        //jtf_idPlaca.setText(String.valueOf(retorno));
        System.out.println("pega -> " + retorno);
        jtf_idveic.setText(String.valueOf(retorno));
        ChamaModelo();

        // TODO add your handling code here:
    }//GEN-LAST:event_jbn_buscarActionPerformed

    private void jft_cnpjKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jft_cnpjKeyReleased
        

        // TODO add your handling code here:
    }//GEN-LAST:event_jft_cnpjKeyReleased

    private void jft_cnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jft_cnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jft_cnpjActionPerformed

    private void jft_cnpjFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jft_cnpjFocusLost
        validaCNPJ valida = new validaCNPJ();
        String cnpj = new String(jft_cnpj.getText());

        boolean g = valida.validaCNPJ(cnpj);

        if (g) {

        } else {
            JOptionPane.showMessageDialog(null, "CNPJ invalido ");
            jft_cnpj.setText("");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jft_cnpjFocusLost

    private void jtf_placaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_placaKeyReleased
        jtf_placa.setText(jtf_placa.getText().toUpperCase());
        
// TODO add your handling code here:
    }//GEN-LAST:event_jtf_placaKeyReleased

    private void jtf_postoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_postoKeyReleased
     jtf_posto.setText(jtf_posto.getText().toUpperCase());
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_postoKeyReleased

    private void jtf_kmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_kmKeyReleased
     jtf_km.setText(jtf_km.getText().toUpperCase());
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_kmKeyReleased

    private void jft_valorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jft_valorKeyReleased
    jft_valor.setText(jft_valor.getText().toUpperCase());        
// TODO add your handling code here:
    }//GEN-LAST:event_jft_valorKeyReleased

    private void jtf_cupomFiscalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_cupomFiscalKeyReleased
      jtf_cupomFiscal.setText(jtf_cupomFiscal.getText().toUpperCase());  
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_cupomFiscalKeyReleased

    private void jtf_combustivelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_combustivelKeyReleased
    jtf_combustivel.setText(jtf_combustivel.getText().toUpperCase());
// TODO add your handling code here:
    }//GEN-LAST:event_jtf_combustivelKeyReleased

    private void jtf_litrosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_litrosKeyReleased
       jtf_litros.setText(jtf_litros.getText().toUpperCase());
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_litrosKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbn_buscar;
    private javax.swing.JButton jbn_cadastro;
    private javax.swing.JButton jbn_fechar3;
    private javax.swing.JButton jbn_limpar;
    private javax.swing.JButton jbn_novo;
    private javax.swing.JFormattedTextField jft_cnpj;
    private javax.swing.JFormattedTextField jft_contato;
    private javax.swing.JFormattedTextField jft_data;
    private javax.swing.JTextField jft_valor;
    private javax.swing.JPanel jpl_opcoes3;
    private javax.swing.JTextField jtf_combustivel;
    private javax.swing.JTextField jtf_cupomFiscal;
    private javax.swing.JTextField jtf_idveic;
    private javax.swing.JTextField jtf_km;
    private javax.swing.JTextField jtf_litros;
    private javax.swing.JTextField jtf_modelo;
    private javax.swing.JTextField jtf_placa;
    private javax.swing.JTextField jtf_posto;
    // End of variables declaration//GEN-END:variables
}
