package view;

import java.awt.Dimension;
import model.bean.validaCNPJ;
import Utilitarios.WebServiceCep;
import model.bean.Motorista;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import model.bean.Cliente;
import model.bean.Validadores;
import model.dao.ClienteDAO;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author total
 */
public class jif_cadastroCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form jif_cadastroMotorista
     */
    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }
    
    public boolean ifNull(){
        if(jtf_empresa.getText().equals("")){
            return false;
        }
       else if(jtf_razaoSocial.getText().equals("")){
            return false;
        }
        if(jft_cnpj.getText().equals("  .   .   /    -  ")){
            return false;
        }
        if(jft_tel2.getText().equals("(  )    -    ")){
            return false;
        }
        if(jft_tel1.getText().equals("(  )     -    ")){
            return false;
        }
        if(jtf_endRua.getText().equals("")){
            return false;
        }
        if(jft_endCEP.getText().equals("")){
            return false;
        }
        
        if(jtf_endBairro.getText().equals("")){
            return false;
        }
        
        if(jtf_endUF.getText().equals("")){
            return false;
        }
        
        if(jtf_usuario.getText().equals("")){
            return false;
        }
        
        if(String.valueOf(jpf_senha.getPassword()).equals("")){
            return false;
        }
        
        if(String.valueOf(jpf_confirmaSenha.getPassword()).equals("")){
            return false;
        }
        
        if(jtf_endCidade.getText().equals("")){
            return false;
        }
        
        if(jtf_responsavel.getText().equals("")){
            return false;
        }
        if(jtf_endNum.getText().equals("")){
            return false;
        }
       
        return true;
    }
    
    Validadores validaT = new Validadores();
    public void limpar() {
        jtf_empresa.setText("");
        jtf_razaoSocial.setText("");
        jft_cnpj.setText("");
        jft_tel2.setText("");
        jft_tel1.setText("");
        jtf_endRua.setText("");
        jft_endCEP.setText("");
        jtf_endBairro.setText("");
        jtf_endNum.setText("");
        jft_tel2.setText("");
        jtf_endBairro.setText("");
        jtf_endUF.setText("");
        jtf_usuario.setText("");
        jpf_senha.setText("");
        jpf_confirmaSenha.setText("");
        jtf_endCidade.setText("");
        jtf_responsavel.setText("");
    }

    public jif_cadastroCliente() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpl_opcoes = new javax.swing.JPanel();
        jbn_fechar = new javax.swing.JButton();
        jbn_limpar = new javax.swing.JButton();
        jbn_cadastro = new javax.swing.JButton();
        jbn_novo = new javax.swing.JButton();
        jlb_empresa = new javax.swing.JLabel();
        jtf_razaoSocial = new javax.swing.JTextField();
        jlb_razaoSocial = new javax.swing.JLabel();
        jtf_empresa = new javax.swing.JTextField();
        jft_cnpj = new javax.swing.JFormattedTextField();
        jlb_cnpj = new javax.swing.JLabel();
        jlb_telefone1 = new javax.swing.JLabel();
        jft_tel1 = new javax.swing.JFormattedTextField();
        jlb_telefone2 = new javax.swing.JLabel();
        jft_tel2 = new javax.swing.JFormattedTextField();
        jlb_rua = new javax.swing.JLabel();
        jtf_endRua = new javax.swing.JTextField();
        jlb_numero = new javax.swing.JLabel();
        jtf_endNum = new javax.swing.JTextField();
        jlb_cep = new javax.swing.JLabel();
        jft_endCEP = new javax.swing.JFormattedTextField();
        jlb_bairro = new javax.swing.JLabel();
        jtf_endBairro = new javax.swing.JTextField();
        jtf_endCidade = new javax.swing.JTextField();
        jlb_cidade = new javax.swing.JLabel();
        jlb_uf = new javax.swing.JLabel();
        jtf_endUF = new javax.swing.JTextField();
        jlb_numero1 = new javax.swing.JLabel();
        jtf_usuario = new javax.swing.JTextField();
        jlb_bairro1 = new javax.swing.JLabel();
        jpf_senha = new javax.swing.JPasswordField();
        jlb_bairro2 = new javax.swing.JLabel();
        jpf_confirmaSenha = new javax.swing.JPasswordField();
        jlb_empresa1 = new javax.swing.JLabel();
        jtf_responsavel = new javax.swing.JTextField();

        setForeground(java.awt.Color.white);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro cliente"));

        jpl_opcoes.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jpl_opcoes.setToolTipText("Opções");

        jbn_fechar.setText("Fechar");
        jbn_fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_fecharActionPerformed(evt);
            }
        });

        jbn_limpar.setText("Limpar");
        jbn_limpar.setEnabled(false);
        jbn_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_limparActionPerformed(evt);
            }
        });

        jbn_cadastro.setText("Cadastrar");
        jbn_cadastro.setEnabled(false);
        jbn_cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_cadastroActionPerformed(evt);
            }
        });

        jbn_novo.setText("Novo");
        jbn_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_novoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpl_opcoesLayout = new javax.swing.GroupLayout(jpl_opcoes);
        jpl_opcoes.setLayout(jpl_opcoesLayout);
        jpl_opcoesLayout.setHorizontalGroup(
            jpl_opcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpl_opcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpl_opcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbn_fechar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbn_limpar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbn_novo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbn_cadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpl_opcoesLayout.setVerticalGroup(
            jpl_opcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpl_opcoesLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jbn_novo)
                .addGap(27, 27, 27)
                .addComponent(jbn_cadastro)
                .addGap(18, 18, 18)
                .addComponent(jbn_limpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                .addComponent(jbn_fechar)
                .addContainerGap())
        );

        jlb_empresa.setText("Empresa:");

        jtf_razaoSocial.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_razaoSocial.setEnabled(false);
        jtf_razaoSocial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_razaoSocialKeyReleased(evt);
            }
        });

        jlb_razaoSocial.setText("Razão social:");

        jtf_empresa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_empresa.setEnabled(false);
        jtf_empresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_empresaActionPerformed(evt);
            }
        });
        jtf_empresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_empresaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_empresaKeyTyped(evt);
            }
        });

        try {
            jft_cnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jft_cnpj.setEnabled(false);
        jft_cnpj.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jft_cnpj.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jft_cnpjFocusLost(evt);
            }
        });
        jft_cnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jft_cnpjActionPerformed(evt);
            }
        });

        jlb_cnpj.setText("CNPJ:");

        jlb_telefone1.setText("Telefone 1:");

        try {
            jft_tel1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jft_tel1.setEnabled(false);
        jft_tel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jlb_telefone2.setText("Telefone 2:");

        try {
            jft_tel2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jft_tel2.setEnabled(false);
        jft_tel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jlb_rua.setText("Rua:");

        jtf_endRua.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_endRua.setEnabled(false);
        jtf_endRua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_endRuaKeyReleased(evt);
            }
        });

        jlb_numero.setText("Nº:");

        jtf_endNum.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_endNum.setEnabled(false);
        jtf_endNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_endNumKeyReleased(evt);
            }
        });

        jlb_cep.setText("CEP:");

        try {
            jft_endCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jft_endCEP.setEnabled(false);
        jft_endCEP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jft_endCEP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jft_endCEPKeyReleased(evt);
            }
        });

        jlb_bairro.setText("Bairro:");

        jtf_endBairro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_endBairro.setEnabled(false);
        jtf_endBairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_endBairroKeyReleased(evt);
            }
        });

        jtf_endCidade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_endCidade.setEnabled(false);
        jtf_endCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_endCidadeKeyReleased(evt);
            }
        });

        jlb_cidade.setText("Cidade:");

        jlb_uf.setText("UF:");

        jtf_endUF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_endUF.setEnabled(false);
        jtf_endUF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_endUFKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_endUFKeyTyped(evt);
            }
        });

        jlb_numero1.setText("Usuario:");

        jtf_usuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_usuario.setEnabled(false);
        jtf_usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_usuarioKeyReleased(evt);
            }
        });

        jlb_bairro1.setText("Senha:");

        jpf_senha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpf_senha.setEnabled(false);
        jpf_senha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jpf_senhaKeyReleased(evt);
            }
        });

        jlb_bairro2.setText("Confirmar senha:");

        jpf_confirmaSenha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpf_confirmaSenha.setEnabled(false);
        jpf_confirmaSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jpf_confirmaSenhaKeyReleased(evt);
            }
        });

        jlb_empresa1.setText("Responsavel:");

        jtf_responsavel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_responsavel.setEnabled(false);
        jtf_responsavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_responsavelActionPerformed(evt);
            }
        });
        jtf_responsavel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_responsavelKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_responsavelKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jlb_empresa)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jtf_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jlb_razaoSocial)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtf_razaoSocial)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jlb_numero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtf_endNum, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlb_bairro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_endBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlb_cep)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jft_endCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jlb_uf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_endUF, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlb_cidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_endCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlb_rua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_endRua, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlb_telefone1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jft_tel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlb_telefone2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jft_tel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlb_cnpj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jft_cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlb_numero1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jlb_bairro1))
                            .addComponent(jlb_bairro2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpf_confirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpf_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlb_empresa1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtf_responsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpl_opcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtf_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlb_empresa))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtf_razaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlb_razaoSocial))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jft_cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlb_cnpj))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jft_tel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlb_telefone1)
                            .addComponent(jft_tel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlb_telefone2))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlb_cep)
                            .addComponent(jft_endCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlb_uf)
                            .addComponent(jtf_endUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlb_cidade)
                            .addComponent(jtf_endCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlb_rua)
                            .addComponent(jtf_endRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlb_numero)
                            .addComponent(jtf_endNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlb_bairro)
                            .addComponent(jtf_endBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtf_responsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlb_empresa1))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlb_numero1)
                            .addComponent(jtf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlb_bairro1)
                            .addComponent(jpf_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlb_bairro2)
                            .addComponent(jpf_confirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jpl_opcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbn_fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_fecharActionPerformed

        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jbn_fecharActionPerformed

    private void jbn_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_limparActionPerformed
        limpar();
        // TODO add your handling code here:
    }//GEN-LAST:event_jbn_limparActionPerformed

    private void jbn_cadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_cadastroActionPerformed
boolean teste = ifNull();
        if(teste){
           // JOptionPane.showMessageDialog(null, "Inserido com sucesso!!!");
            Cliente c = new Cliente();
            ClienteDAO cd = new ClienteDAO();

            c.setEmpresa(jtf_empresa.getText().toUpperCase());
            c.setRazaoSocial(jtf_razaoSocial.getText().toUpperCase());
            c.setCnpj(jft_cnpj.getText());
            c.setTelefone1(jft_tel1.getText().toUpperCase());
            c.setTelefone2(jft_tel2.getText().toUpperCase());
            c.setRua(jtf_endRua.getText().toUpperCase());
            c.setCep(jft_endCEP.getText());
            c.setBairro(jtf_endBairro.getText().toUpperCase());
            c.setNumero(Integer.parseInt(jtf_endNum.getText()));
            c.setCidade(jtf_endCidade.getText().toUpperCase());
            c.setResponsavel(jtf_responsavel.getText().toUpperCase());
            c.setUf(jtf_endUF.getText().toUpperCase());
            c.setUsuario(jtf_usuario.getText());
            c.setSenha(String.valueOf(jpf_senha.getPassword()));
            String senha1 = String.valueOf(jpf_senha.getPassword());
            String senha2 = String.valueOf(jpf_confirmaSenha.getPassword());
            if(senha1.equals(senha2)){
                cd.inserir(c);
                limpar();
                JOptionPane.showMessageDialog(null, "Inserido com sucesso!!!");
            }else{
                JOptionPane.showMessageDialog(null, "Senhas divergentes");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos!!!" , "ATENÇÃO",JOptionPane.WARNING_MESSAGE);
        }
        

        
        //JOptionPane.showMessageDialog(null, "Inserido com sucesso!");
    }//GEN-LAST:event_jbn_cadastroActionPerformed

    private void jbn_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_novoActionPerformed
        jbn_cadastro.setEnabled(true);
        jbn_limpar.setEnabled(true);
        jtf_empresa.setEnabled(true);
        jtf_razaoSocial.setEnabled(true);
        jft_cnpj.setEnabled(true);
        jft_tel2.setEnabled(true);
        jft_tel1.setEnabled(true);
        jtf_endRua.setEnabled(true);
        jft_endCEP.setEnabled(true);
        jtf_endBairro.setEnabled(true);
        jtf_endNum.setEnabled(true);
        jft_tel2.setEnabled(true);
        jtf_endCidade.setEnabled(true);
        jtf_usuario.setEnabled(true);
        jpf_senha.setEnabled(true);
        jpf_confirmaSenha.setEnabled(true);
        jtf_endUF.setEnabled(true);
        jtf_responsavel.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jbn_novoActionPerformed

    private void jtf_empresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_empresaActionPerformed
        // jtf_empresa.setText(jtf_empresa.getText().toUpperCase());
// TODO add your handling code here:
    }//GEN-LAST:event_jtf_empresaActionPerformed

    private void jtf_empresaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_empresaKeyTyped
//jtf_empresa.setText(jtf_empresa.getText().toUpperCase());
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_empresaKeyTyped

    private void jtf_empresaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_empresaKeyReleased
        jtf_empresa.setText(jtf_empresa.getText().toUpperCase());
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_empresaKeyReleased

    private void jft_cnpjFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jft_cnpjFocusLost
        validaCNPJ valida = new validaCNPJ();
        String cnpj = new String(jft_cnpj.getText());

        boolean g = valida.validaCNPJ(cnpj);

        if (g) {

        } else {
            JOptionPane.showMessageDialog(null, "CNPJ invalido ");
            jft_cnpj.setText("");
        }

// TODO add your handling code here:
    }//GEN-LAST:event_jft_cnpjFocusLost

    private void jft_endCEPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jft_endCEPKeyReleased
        String cp = jft_endCEP.getText();
        cp = cp.replaceAll("\\D*", ""); //ignora qualquer coisa que não seja numero.  
        int cont = cp.length();

        if (cont == 8) {
            try {
                correio();
            } catch (Error e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jft_endCEPKeyReleased

    private void jtf_responsavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_responsavelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_responsavelActionPerformed

    private void jtf_responsavelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_responsavelKeyReleased
        jtf_responsavel.setText(jtf_responsavel.getText().toUpperCase());
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_responsavelKeyReleased

    private void jtf_responsavelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_responsavelKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_responsavelKeyTyped

    private void jtf_razaoSocialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_razaoSocialKeyReleased
         jtf_razaoSocial.setText(jtf_razaoSocial.getText().toUpperCase());
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_razaoSocialKeyReleased

    private void jtf_endUFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_endUFKeyTyped
        jtf_endUF.setText(jtf_endUF.getText().toUpperCase());
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_endUFKeyTyped

    private void jtf_endCidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_endCidadeKeyReleased
        jtf_endCidade.setText(jtf_endCidade.getText().toUpperCase());
        if(validaT.validaTam(jtf_endCidade.getText(), 100)){
            String novo = validaT.diminui(jtf_endCidade.getText(), 100);
            jtf_endCidade.setText(novo);
            JOptionPane.showMessageDialog(null, "A quantidade de caracteres exede o limite permitido", "ATENÇÃO!!!", JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_endCidadeKeyReleased

    private void jtf_endRuaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_endRuaKeyReleased
        jtf_endRua.setText(jtf_endRua.getText().toUpperCase());
         if(validaT.validaTam(jtf_endRua.getText(), 100)){
            String novo = validaT.diminui(jtf_endRua.getText(), 100);
            jtf_endRua.setText(novo);
            JOptionPane.showMessageDialog(null, "A quantidade de caracteres exede o limite permitido", "ATENÇÃO!!!", JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_endRuaKeyReleased

    private void jtf_endNumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_endNumKeyReleased
    jtf_endNum.setText(jtf_endNum.getText().toUpperCase());
     if(validaT.validaTam(jtf_endNum.getText(), 10)){
            String novo = validaT.diminui(jtf_endNum.getText(), 10);
            jtf_endNum.setText(novo);
            JOptionPane.showMessageDialog(null, "A quantidade de caracteres exede o limite permitido", "ATENÇÃO!!!", JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_endNumKeyReleased

    private void jtf_endBairroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_endBairroKeyReleased
        jtf_endBairro.setText(jtf_endBairro.getText().toUpperCase());
         if(validaT.validaTam(jtf_endBairro.getText(), 100)){
            String novo = validaT.diminui(jtf_endBairro.getText(), 100);
            jtf_endBairro.setText(novo);
            JOptionPane.showMessageDialog(null, "A quantidade de caracteres exede o limite permitido", "ATENÇÃO!!!", JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_endBairroKeyReleased

    private void jft_cnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jft_cnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jft_cnpjActionPerformed

    private void jtf_endUFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_endUFKeyReleased
        // TODO add your handling code here:
        jtf_endUF.setText(jtf_endUF.getText().toUpperCase());
     if(validaT.validaTam(jtf_endUF.getText(), 2)){
            String novo = validaT.diminui(jtf_endUF.getText(), 2);
            jtf_endUF.setText(novo);
            JOptionPane.showMessageDialog(null, "A quantidade de caracteres exede o limite permitido", "ATENÇÃO!!!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jtf_endUFKeyReleased

    private void jtf_usuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_usuarioKeyReleased
        // TODO add your handling code here:
        
     if(validaT.validaTam(jtf_usuario.getText(), 20)){
            String novo = validaT.diminui(jtf_usuario.getText(), 20);
            jtf_usuario.setText(novo);
            JOptionPane.showMessageDialog(null, "A quantidade de caracteres exede o limite permitido", "ATENÇÃO!!!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jtf_usuarioKeyReleased

    private void jpf_senhaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpf_senhaKeyReleased
        // TODO add your handling code here:
        if(validaT.validaTam(String.valueOf(jpf_senha.getPassword()), 10)){
            
            jpf_senha.setText("");
            JOptionPane.showMessageDialog(null, "A quantidade de caracteres exede o limite permitido", "ATENÇÃO!!!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jpf_senhaKeyReleased

    private void jpf_confirmaSenhaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpf_confirmaSenhaKeyReleased
        if(validaT.validaTam(String.valueOf(jpf_confirmaSenha.getPassword()), 10)){
            
            jpf_confirmaSenha.setText("");
            JOptionPane.showMessageDialog(null, "A quantidade de caracteres exede o limite permitido", "ATENÇÃO!!!", JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jpf_confirmaSenhaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbn_cadastro;
    private javax.swing.JButton jbn_fechar;
    private javax.swing.JButton jbn_limpar;
    private javax.swing.JButton jbn_novo;
    private javax.swing.JFormattedTextField jft_cnpj;
    private javax.swing.JFormattedTextField jft_endCEP;
    private javax.swing.JFormattedTextField jft_tel1;
    private javax.swing.JFormattedTextField jft_tel2;
    private javax.swing.JLabel jlb_bairro;
    private javax.swing.JLabel jlb_bairro1;
    private javax.swing.JLabel jlb_bairro2;
    private javax.swing.JLabel jlb_cep;
    private javax.swing.JLabel jlb_cidade;
    private javax.swing.JLabel jlb_cnpj;
    private javax.swing.JLabel jlb_empresa;
    private javax.swing.JLabel jlb_empresa1;
    private javax.swing.JLabel jlb_numero;
    private javax.swing.JLabel jlb_numero1;
    private javax.swing.JLabel jlb_razaoSocial;
    private javax.swing.JLabel jlb_rua;
    private javax.swing.JLabel jlb_telefone1;
    private javax.swing.JLabel jlb_telefone2;
    private javax.swing.JLabel jlb_uf;
    private javax.swing.JPasswordField jpf_confirmaSenha;
    private javax.swing.JPasswordField jpf_senha;
    private javax.swing.JPanel jpl_opcoes;
    private javax.swing.JTextField jtf_empresa;
    private javax.swing.JTextField jtf_endBairro;
    private javax.swing.JTextField jtf_endCidade;
    private javax.swing.JTextField jtf_endNum;
    private javax.swing.JTextField jtf_endRua;
    private javax.swing.JTextField jtf_endUF;
    private javax.swing.JTextField jtf_razaoSocial;
    private javax.swing.JTextField jtf_responsavel;
    private javax.swing.JTextField jtf_usuario;
    // End of variables declaration//GEN-END:variables
public void correio() {

        String cep = jft_endCEP.getText();

        WebServiceCep webServiceCep = WebServiceCep.searchCep(cep);

        if (webServiceCep.wasSuccessful()) {

            jtf_endRua.setText(webServiceCep.getLogradouroFull().toUpperCase());
            jtf_endBairro.setText(webServiceCep.getBairro().toUpperCase());
            jtf_endCidade.setText(webServiceCep.getCidade().toUpperCase());
            jtf_endUF.setText(webServiceCep.getUf().toUpperCase());

        } else {
            JOptionPane.showMessageDialog(null, webServiceCep.getResultText());

        }

    }

}
