/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Dimension;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Veiculo;
import model.dao.VeiculoDAO;

/**
 *
 * @author total
 */
public class jif_consultaVeiculo extends javax.swing.JInternalFrame {
    
    public jif_consultaVeiculo() throws ClassNotFoundException {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jtb_tabela.getModel();
        jtb_tabela.setRowSorter(new TableRowSorter(modelo));
        
        readJTable();
    }
    
    public void readJTable() throws ClassNotFoundException {
        DefaultTableModel modelo = (DefaultTableModel) jtb_tabela.getModel();
        modelo.setNumRows(0);
        VeiculoDAO vd = new VeiculoDAO();
        
        for (Veiculo v : vd.Buscar()) {
            modelo.addRow(new Object[]{
                v.getId_veic(),
                v.getMarca(),
                v.getModelo(),
                v.getAno(),
                v.getPlaca(),
                v.getChassi(),
                v.getCor(),
                v.getKm(),
                v.getVeicAlugado(),
                v.getTipo()            
            });
        }
    }

    /**
     * Creates new form jif_consultaVeiculo
     */
    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jp_menu = new javax.swing.JPanel();
        jlb_pesquisar = new javax.swing.JLabel();
        jtf_pesquisar = new javax.swing.JTextField();
        jbn_buscar = new javax.swing.JButton();
        jbn_atualizar = new javax.swing.JButton();
        jbn_fechar = new javax.swing.JButton();
        jbn_deletar = new javax.swing.JButton();
        jtf_deletar = new javax.swing.JTextField();
        jlb_placa = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtb_tabela = new javax.swing.JTable();

        jp_menu.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlb_pesquisar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlb_pesquisar.setText("Pesquisa:");

        jtf_pesquisar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jbn_buscar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbn_buscar.setText("Buscar");

        jbn_atualizar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbn_atualizar.setText("Atualizar");
        jbn_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_atualizarActionPerformed(evt);
            }
        });

        jbn_fechar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbn_fechar.setText("Fechar");
        jbn_fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_fecharActionPerformed(evt);
            }
        });

        jbn_deletar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbn_deletar.setText("Deletar");
        jbn_deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_deletarActionPerformed(evt);
            }
        });

        jlb_placa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlb_placa.setText("Placa:");

        javax.swing.GroupLayout jp_menuLayout = new javax.swing.GroupLayout(jp_menu);
        jp_menu.setLayout(jp_menuLayout);
        jp_menuLayout.setHorizontalGroup(
            jp_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_menuLayout.createSequentialGroup()
                .addComponent(jlb_pesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbn_buscar)
                .addGap(38, 38, 38)
                .addComponent(jbn_atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jlb_placa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtf_deletar, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbn_deletar)
                .addGap(202, 202, 202)
                .addComponent(jbn_fechar))
        );
        jp_menuLayout.setVerticalGroup(
            jp_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_menuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbn_fechar)
                    .addComponent(jlb_pesquisar)
                    .addComponent(jtf_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbn_buscar)
                    .addComponent(jbn_deletar)
                    .addComponent(jtf_deletar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlb_placa)
                    .addComponent(jbn_atualizar))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jtb_tabela.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jtb_tabela.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtb_tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Veiculo", "Marca", "Modelo", "Ano", "Placa", "Chassi", "Cor", "KM", "Alugado", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtb_tabela);
        if (jtb_tabela.getColumnModel().getColumnCount() > 0) {
            jtb_tabela.getColumnModel().getColumn(0).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jp_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbn_fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_fecharActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jbn_fecharActionPerformed

    private void jbn_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_atualizarActionPerformed
        Veiculo v = new Veiculo();
        VeiculoDAO vd;
        try {
            vd = new VeiculoDAO();
            v.setChassi((String) jtb_tabela.getValueAt(jtb_tabela.getSelectedRow(), 5));
            v.setPlaca((String) jtb_tabela.getValueAt(jtb_tabela.getSelectedRow(), 4));
            v.setModelo((String) jtb_tabela.getValueAt(jtb_tabela.getSelectedRow(), 2));
            v.setMarca((String) jtb_tabela.getValueAt(jtb_tabela.getSelectedRow(), 1));
            v.setCor((String) jtb_tabela.getValueAt(jtb_tabela.getSelectedRow(), 6));
            v.setTipo((String) jtb_tabela.getValueAt(jtb_tabela.getSelectedRow(), 9));
            v.setAno((int) jtb_tabela.getValueAt(jtb_tabela.getSelectedRow(), 3));
            v.setVeicAlugado((String) jtb_tabela.getValueAt(jtb_tabela.getSelectedRow(), 8));
            v.setKm((int) jtb_tabela.getValueAt(jtb_tabela.getSelectedRow(), 7));
            v.setId_veic((int) jtb_tabela.getValueAt(jtb_tabela.getSelectedRow(), 0));
            vd.Alterar(v);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(jif_consultaVeiculo.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jbn_atualizarActionPerformed

    private void jbn_deletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_deletarActionPerformed
        Veiculo v = new Veiculo();
        VeiculoDAO vd;
        try {
            vd = new VeiculoDAO();           
            v.setPlaca(jtf_deletar.getText());          
            vd.Apagar(v);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(jif_consultaVeiculo.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jbn_deletarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbn_atualizar;
    private javax.swing.JButton jbn_buscar;
    private javax.swing.JButton jbn_deletar;
    private javax.swing.JButton jbn_fechar;
    private javax.swing.JLabel jlb_pesquisar;
    private javax.swing.JLabel jlb_placa;
    private javax.swing.JPanel jp_menu;
    private javax.swing.JTable jtb_tabela;
    private javax.swing.JTextField jtf_deletar;
    private javax.swing.JTextField jtf_pesquisar;
    // End of variables declaration//GEN-END:variables
}
