package view;

import connection.TesteBanco;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import model.bean.Pneu;
import model.bean.Validadores;
import model.bean.Veiculo;
import model.dao.PneuDAO;
import model.dao.VeiculoDAO;

/**
 *
 * @author marcu
 */
public class jif_pneu extends javax.swing.JInternalFrame {

    /**
     * Creates new form jif_pneu
     */
    public void fechar() {
        this.dispose();
    }
    
    
    
    Validadores validaT = new Validadores();
    
    public boolean ifNull(){
        if(jtf_aro.equals("")){
            return false;
        }
        if(jtf_km.equals("")){
            return false;
        }
        
        if(jtf_largura.equals("")){
            return false;
        }
        if(jtf_perfil.equals("")){
            return false;
        }
        if(jtf_placa.equals("")){
            return false;
        }
        if(jtf_serie.equals("")){
            return false;
        }
        if(jtf_sulcos.equals("")){
            return false;
        }
        if(jtf_dataFabricacao.equals("")){
            return false;
        }
        if(jtf_veiculoModelo.equals("")){
            return false;
        }
        
        
        return true;
    }
    
    public void novo() {
        jtf_aro.setEnabled(true);
        jtf_km.setEnabled(true);
        jtf_largura.setEnabled(true);
        jtf_perfil.setEnabled(true);
        jtf_placa.setEnabled(true);
        jtf_serie.setEnabled(true);
        jtf_sulcos.setEnabled(true);
        jtf_dataFabricacao.setEnabled(true);
        jtf_veiculoModelo.setEnabled(true);
        
        
        jButton4.setEnabled(false);
        
    }
    
    public void limpar() {
        jtf_aro.setText("");
        jtf_km.setText("");
        jtf_largura.setText("");
        jtf_perfil.setText("");
        jtf_placa.setText("");
        jtf_serie.setText("");
        jtf_sulcos.setText("");
        jtf_dataFabricacao.setText("");
        jtf_veiculoModelo.setText("");
        jtf_idVeic.setText("");
        jButton4.setEnabled(true);
    }

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    public jif_pneu() {
        initComponents();
        jtf_idVeic.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jbn_cadastrar = new javax.swing.JButton();
        jbn_limpar = new javax.swing.JButton();
        jbn_fechar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtf_placa = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jtf_veiculoModelo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtf_serie = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtf_dataFabricacao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtf_km = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtf_aro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtf_sulcos = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtf_largura = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtf_perfil = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtf_idVeic = new javax.swing.JTextField();
        jbn_help = new javax.swing.JButton();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setVisible(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro pneu"));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jbn_cadastrar.setText("Cadastrar");
        jbn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_cadastrarActionPerformed(evt);
            }
        });

        jbn_limpar.setText("Limpar");
        jbn_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_limparActionPerformed(evt);
            }
        });

        jbn_fechar.setText("Fechar");
        jbn_fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_fecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbn_cadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbn_limpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jbn_fechar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbn_cadastrar)
                .addGap(18, 18, 18)
                .addComponent(jbn_limpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(jbn_fechar)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Placa:");

        jtf_placa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_placa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_placaKeyReleased(evt);
            }
        });

        jButton4.setText("Buscar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jtf_veiculoModelo.setEditable(false);
        jtf_veiculoModelo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_veiculoModelo.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Numero de serie:");

        jtf_serie.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_serie.setEnabled(false);
        jtf_serie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_serieKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Data fabricação:");

        jtf_dataFabricacao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_dataFabricacao.setEnabled(false);
        jtf_dataFabricacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_dataFabricacaoKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Quilometragem:");

        jtf_km.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_km.setEnabled(false);
        jtf_km.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_kmActionPerformed(evt);
            }
        });
        jtf_km.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_kmKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Aro:");

        jtf_aro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_aro.setEnabled(false);
        jtf_aro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_aroKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Sulcos:");

        jtf_sulcos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_sulcos.setEnabled(false);
        jtf_sulcos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_sulcosKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Largura:");

        jtf_largura.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_largura.setEnabled(false);
        jtf_largura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_larguraActionPerformed(evt);
            }
        });
        jtf_largura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_larguraKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Perfil:");

        jtf_perfil.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_perfil.setEnabled(false);
        jtf_perfil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_perfilKeyReleased(evt);
            }
        });

        jLabel9.setText("Modelo:");

        jtf_idVeic.setEnabled(false);

        jbn_help.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbn_help.setText("?");
        jbn_help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_helpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_largura, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtf_idVeic, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jtf_placa, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jbn_help))
                                    .addComponent(jtf_veiculoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtf_km, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtf_aro))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtf_serie, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtf_sulcos, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 6, Short.MAX_VALUE)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtf_dataFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(jtf_sulcos, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jtf_placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton4)
                                    .addComponent(jbn_help))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtf_veiculoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jtf_serie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jtf_dataFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jtf_km, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jtf_aro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(jtf_perfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtf_idVeic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(jtf_largura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbn_fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_fecharActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jbn_fecharActionPerformed

    private void jbn_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_limparActionPerformed
        limpar();
        // TODO add your handling code here:
    }//GEN-LAST:event_jbn_limparActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        /*REALIZAR BUSCAR NA PLACA DO VEICULO PARA RETORNAR O ID DO VEICULO PARA ASSSOCIAÇÃO COM O PNEU*/
        Veiculo v = new Veiculo();
        VeiculoDAO vd = null;
        try {
            vd = new VeiculoDAO();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(jif_pneu.class.getName()).log(Level.SEVERE, null, ex);
        }
        v.setPlaca(jtf_placa.getText());
        int retorno = 0;
        try {
            retorno = vd.BuscarVeicAlugado(v.getPlaca());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao buscar veiculo" + ex);
        }
        try {
            Connection con = null;
            con = TesteBanco.getConnection();
            String sql = "SELECT  modelo FROM Veiculos WHERE idVeic = ?";
            PreparedStatement stmt = null;
            ResultSet rs = null;
            
           
            stmt = con.prepareStatement(sql);
            stmt.setInt(1, retorno);
            rs = stmt.executeQuery();
            if (rs.next()) {       
                novo();
                jButton4.setEnabled(false);
                jtf_veiculoModelo.setText(rs.getString("modelo"));                
            }

        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Erro no select completo de veiculo" + ex);
        }

        jtf_idVeic.setText(String.valueOf(retorno));

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jbn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_cadastrarActionPerformed
        
        boolean teste = ifNull();
        if(teste){
            Pneu p = new Pneu();
        PneuDAO pd = new PneuDAO();

        p.setDtProduzido(Integer.parseInt(jtf_dataFabricacao.getText()));
        p.setIdVeic(Integer.parseInt(jtf_idVeic.getText()));
        p.setLargura(jtf_largura.getText());
        p.setAltura(jtf_perfil.getText());
        p.setAro(jtf_aro.getText());
        p.setProfundidade(Float.parseFloat(jtf_sulcos.getText()));
        p.setnSerie(jtf_serie.getText());
        p.setKmPneu(Integer.parseInt(jtf_km.getText()));
        pd.inserir(p);
        limpar();
        }else{
            JOptionPane.showMessageDialog(null, "Favor preencher todos os campos para realizar o cadastro!", "ATENÇÃO",JOptionPane.WARNING_MESSAGE );
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jbn_cadastrarActionPerformed

    private void jtf_serieKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_serieKeyReleased

        jtf_serie.setText(jtf_serie.getText().toUpperCase());
        if(validaT.validaTam(jtf_serie.getText(), 10)){
            String novo = validaT.diminui(jtf_serie.getText(), 10);
            jtf_serie.setText(novo);
            JOptionPane.showMessageDialog(null, "A quantidade de caracteres exede o limite permitido", "ATENÇÃO!!!", JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_serieKeyReleased

    private void jtf_larguraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_larguraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_larguraActionPerformed

    private void jtf_placaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_placaKeyReleased
        jtf_placa.setText(jtf_placa.getText().toUpperCase());
        if(validaT.validaTam(jtf_placa.getText(), 8)){
            String novo = validaT.diminui(jtf_placa.getText(), 8);
            jtf_placa.setText(novo);
            JOptionPane.showMessageDialog(null, "A quantidade de caracteres exede o limite permitido", "ATENÇÃO!!!", JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_placaKeyReleased

    private void jtf_dataFabricacaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_dataFabricacaoKeyReleased
        jtf_dataFabricacao.setText(jtf_dataFabricacao.getText().toUpperCase());
        if(validaT.validaTam(jtf_dataFabricacao.getText(), 10)){
            String novo = validaT.diminui(jtf_dataFabricacao.getText(), 10);
            jtf_dataFabricacao.setText(novo);
            JOptionPane.showMessageDialog(null, "A quantidade de caracteres exede o limite permitido", "ATENÇÃO!!!", JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_dataFabricacaoKeyReleased

    private void jtf_kmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_kmActionPerformed
      
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_kmActionPerformed

    private void jtf_kmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_kmKeyReleased
        jtf_km.setText(jtf_km.getText().toUpperCase());
        if(validaT.validaTam(jtf_km.getText(), 10)){
            String novo = validaT.diminui(jtf_km.getText(), 10);
            jtf_km.setText(novo);
            JOptionPane.showMessageDialog(null, "A quantidade de caracteres exede o limite permitido", "ATENÇÃO!!!", JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_kmKeyReleased

    private void jtf_aroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_aroKeyReleased
         jtf_aro.setText(jtf_aro.getText().toUpperCase());
        if(validaT.validaTam(jtf_aro.getText(), 2)){
            String novo = validaT.diminui(jtf_aro.getText(), 2);
            jtf_aro.setText(novo);
            JOptionPane.showMessageDialog(null, "A quantidade de caracteres exede o limite permitido", "ATENÇÃO!!!", JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_aroKeyReleased

    private void jtf_sulcosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_sulcosKeyReleased
          jtf_sulcos.setText(jtf_sulcos.getText().toUpperCase());
        if(validaT.validaTam(jtf_sulcos.getText(), 4)){
            String novo = validaT.diminui(jtf_sulcos.getText(), 4);
            jtf_sulcos.setText(novo);
            JOptionPane.showMessageDialog(null, "A quantidade de caracteres exede o limite permitido", "ATENÇÃO!!!", JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_sulcosKeyReleased

    private void jtf_larguraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_larguraKeyReleased
         jtf_largura.setText(jtf_largura.getText().toUpperCase());
        if(validaT.validaTam(jtf_largura.getText(), 3)){
            String novo = validaT.diminui(jtf_largura.getText(), 3);
            jtf_largura.setText(novo);
            JOptionPane.showMessageDialog(null, "A quantidade de caracteres exede o limite permitido", "ATENÇÃO!!!", JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_larguraKeyReleased

    private void jtf_perfilKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_perfilKeyReleased
          jtf_perfil.setText(jtf_perfil.getText().toUpperCase());
        if(validaT.validaTam(jtf_perfil.getText(), 2)){
            String novo = validaT.diminui(jtf_perfil.getText(), 2);
            jtf_perfil.setText(novo);
            JOptionPane.showMessageDialog(null, "A quantidade de caracteres exede o limite permitido", "ATENÇÃO!!!", JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_perfilKeyReleased

    private void jbn_helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_helpActionPerformed
        jif_helPneu pneu = new jif_helPneu();
         ((BasicInternalFrameUI)pneu.getUI()).setNorthPane(null);
        getParent().add(pneu);
        pneu.moveToFront();
        pneu.setLocation(880, 35);
        pneu.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jbn_helpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbn_cadastrar;
    private javax.swing.JButton jbn_fechar;
    private javax.swing.JButton jbn_help;
    private javax.swing.JButton jbn_limpar;
    private javax.swing.JTextField jtf_aro;
    private javax.swing.JTextField jtf_dataFabricacao;
    private javax.swing.JTextField jtf_idVeic;
    private javax.swing.JTextField jtf_km;
    private javax.swing.JTextField jtf_largura;
    private javax.swing.JTextField jtf_perfil;
    private javax.swing.JTextField jtf_placa;
    private javax.swing.JTextField jtf_serie;
    private javax.swing.JTextField jtf_sulcos;
    private javax.swing.JTextField jtf_veiculoModelo;
    // End of variables declaration//GEN-END:variables
}
