package view;

import java.awt.Dimension;
import javax.swing.JOptionPane;
import model.bean.Cliente;
import model.bean.VeiculoAlugado;
import model.dao.AluguelDAO;
import model.dao.ClienteDAO;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author total
 */
public class jif_cadastroAluguel extends javax.swing.JInternalFrame {

    /**
     * Creates new form jif_cadastroMotorista
     */
    
    
    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
        jtf_alugado.setVisible(false);
    }

    public boolean ifNull(){
        if(jtf_placa.getText().equals("")){
            return false;
        }
        if(jtf_chassi.getText().equals("")){
            return false;
        }
        if(jtf_marca.getText().equals("")){
            return false;
        }
        if(jft_ano.getText().equals("    ")){
            return false;
        }
        if(jtf_quilometragem.getText().equals("")){
            return false;
        }
        if(jtf_tipo.getText().equals("")){
            return false;
        }
        if(jtf_modelo.getText().equals("")){
            return false;
        }
        if(jtf_cor1.getText().equals("")){
            return false;
        }
      
        return true;
    }
    
    public void limpar() {
        jtf_placa.setText("");
        jtf_chassi.setText("");
        jtf_marca.setText("");
        jft_ano.setText("");
        jtf_quilometragem.setText("");
        jtf_quilometragem.setText("");
        jtf_tipo.setText("");
        jtf_modelo.setText("");
        jtf_cor1.setText("");
    }

    public jif_cadastroAluguel() {

        initComponents();
        jtf_alugado.setText("SIM");
        
        jtf_alugado.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jpl_opcoes = new javax.swing.JPanel();
        jbn_fechar = new javax.swing.JButton();
        jbn_limpar = new javax.swing.JButton();
        jbn_cadastro = new javax.swing.JButton();
        jbn_novo = new javax.swing.JButton();
        jlb_placa = new javax.swing.JLabel();
        jtf_chassi = new javax.swing.JTextField();
        jlb_cor = new javax.swing.JLabel();
        jtf_placa = new javax.swing.JTextField();
        jlb_marca = new javax.swing.JLabel();
        jtf_marca = new javax.swing.JTextField();
        jlb_ano = new javax.swing.JLabel();
        jft_ano = new javax.swing.JFormattedTextField();
        jlb_quilometragem = new javax.swing.JLabel();
        jtf_quilometragem = new javax.swing.JTextField();
        jtf_modelo = new javax.swing.JTextField();
        jlb_modelo = new javax.swing.JLabel();
        jlb_tipo = new javax.swing.JLabel();
        jtf_tipo = new javax.swing.JTextField();
        jtf_cor1 = new javax.swing.JTextField();
        jlb_chassi = new javax.swing.JLabel();
        jtf_alugado = new javax.swing.JTextField();

        jToggleButton1.setText("jToggleButton1");

        setForeground(java.awt.Color.white);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro veiculo alugado"));

        jpl_opcoes.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jpl_opcoes.setToolTipText("Opções");

        jbn_fechar.setText("Fechar");
        jbn_fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_fecharActionPerformed(evt);
            }
        });

        jbn_limpar.setText("Limpar");
        jbn_limpar.setEnabled(false);
        jbn_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_limparActionPerformed(evt);
            }
        });

        jbn_cadastro.setText("Cadastrar");
        jbn_cadastro.setEnabled(false);
        jbn_cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_cadastroActionPerformed(evt);
            }
        });

        jbn_novo.setText("Novo");
        jbn_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_novoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpl_opcoesLayout = new javax.swing.GroupLayout(jpl_opcoes);
        jpl_opcoes.setLayout(jpl_opcoesLayout);
        jpl_opcoesLayout.setHorizontalGroup(
            jpl_opcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpl_opcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpl_opcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbn_fechar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbn_limpar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbn_novo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbn_cadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpl_opcoesLayout.setVerticalGroup(
            jpl_opcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpl_opcoesLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jbn_novo)
                .addGap(27, 27, 27)
                .addComponent(jbn_cadastro)
                .addGap(18, 18, 18)
                .addComponent(jbn_limpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jbn_fechar)
                .addContainerGap())
        );

        jlb_placa.setText("Placa:");

        jtf_chassi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_chassi.setEnabled(false);
        jtf_chassi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_chassiActionPerformed(evt);
            }
        });
        jtf_chassi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_chassiKeyReleased(evt);
            }
        });

        jlb_cor.setText("Cor:");

        jtf_placa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_placa.setEnabled(false);
        jtf_placa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_placaKeyReleased(evt);
            }
        });

        jlb_marca.setText("Marca:");

        jtf_marca.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_marca.setEnabled(false);
        jtf_marca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_marcaKeyReleased(evt);
            }
        });

        jlb_ano.setText("Ano:");

        try {
            jft_ano.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jft_ano.setEnabled(false);
        jft_ano.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jft_ano.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jft_anoKeyReleased(evt);
            }
        });

        jlb_quilometragem.setText("Quilometragem:");

        jtf_quilometragem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_quilometragem.setEnabled(false);
        jtf_quilometragem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_quilometragemKeyReleased(evt);
            }
        });

        jtf_modelo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_modelo.setEnabled(false);
        jtf_modelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_modeloKeyReleased(evt);
            }
        });

        jlb_modelo.setText("Modelo:");

        jlb_tipo.setText("Tipo:");

        jtf_tipo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_tipo.setEnabled(false);
        jtf_tipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_tipoKeyReleased(evt);
            }
        });

        jtf_cor1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_cor1.setEnabled(false);
        jtf_cor1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_cor1KeyReleased(evt);
            }
        });

        jlb_chassi.setText("Chassi:");

        jtf_alugado.setEditable(false);
        jtf_alugado.setEnabled(false);
        jtf_alugado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_alugadoActionPerformed(evt);
            }
        });
        jtf_alugado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_alugadoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jtf_alugado, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlb_ano)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jft_ano, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jlb_tipo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jlb_marca)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtf_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jlb_modelo))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jlb_placa)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtf_placa, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(119, 119, 119)
                                        .addComponent(jlb_cor)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtf_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtf_cor1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlb_quilometragem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_quilometragem, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlb_chassi)
                                .addGap(32, 32, 32)
                                .addComponent(jtf_chassi, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)))))
                .addGap(79, 79, 79)
                .addComponent(jpl_opcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpl_opcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtf_alugado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtf_placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlb_placa)
                            .addComponent(jlb_cor)
                            .addComponent(jtf_cor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlb_marca)
                            .addComponent(jtf_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlb_modelo)
                            .addComponent(jtf_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlb_ano)
                            .addComponent(jft_ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlb_tipo)
                            .addComponent(jtf_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlb_quilometragem)
                            .addComponent(jtf_quilometragem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_chassi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlb_chassi))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbn_fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_fecharActionPerformed

        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jbn_fecharActionPerformed

    private void jbn_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_limparActionPerformed
        limpar();
        // TODO add your handling code here:
    }//GEN-LAST:event_jbn_limparActionPerformed

    private void jbn_cadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_cadastroActionPerformed

        
        boolean teste = ifNull();
        if(teste){
           // JOptionPane.showMessageDialog(null, "Inserido com sucesso!!!");
            VeiculoAlugado v = new VeiculoAlugado();
        AluguelDAO vd;

        vd = new AluguelDAO();
        v.setChassi(jtf_chassi.getText());
        v.setPlaca(jtf_placa.getText());
        v.setModelo(jtf_modelo.getText());
        v.setMarca(jtf_marca.getText());
        v.setCor(jtf_cor1.getText());
        v.setTipo(jtf_tipo.getText());
        v.setAno(Integer.parseInt(jft_ano.getText()));
        v.setVeicAlugado(String.valueOf(jtf_alugado.getText()));
        v.setKm(Integer.parseInt(jtf_quilometragem.getText()));
        vd.inserir(v);
        limpar();
                JOptionPane.showMessageDialog(null, "Inserido com sucesso!!!");
            
            }
        else{
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos!!!" , "ATENÇÃO",JOptionPane.WARNING_MESSAGE);
        }

        //readJTable();

    }//GEN-LAST:event_jbn_cadastroActionPerformed

    private void jbn_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_novoActionPerformed
        jbn_cadastro.setEnabled(true);
        jbn_limpar.setEnabled(true);
        jtf_placa.setEnabled(true);
        jtf_chassi.setEnabled(true);
        jtf_marca.setEnabled(true);
        jft_ano.setEnabled(true);
        jtf_quilometragem.setEnabled(true);
        jtf_modelo.setEnabled(true);
        jtf_tipo.setEnabled(true);
        jtf_cor1.setEnabled(true);
        jtf_alugado.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jbn_novoActionPerformed

    private void jtf_alugadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_alugadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_alugadoActionPerformed

    private void jtf_alugadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_alugadoKeyReleased
        jtf_alugado.setText(jtf_alugado.getText().toUpperCase());
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_alugadoKeyReleased

    private void jtf_placaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_placaKeyReleased
        jtf_placa.setText(jtf_placa.getText().toUpperCase());
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_placaKeyReleased

    private void jtf_cor1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_cor1KeyReleased
        jtf_cor1.setText(jtf_cor1.getText().toUpperCase());
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_cor1KeyReleased

    private void jtf_marcaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_marcaKeyReleased
        jtf_marca.setText(jtf_marca.getText().toUpperCase());
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_marcaKeyReleased

    private void jtf_modeloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_modeloKeyReleased
        jtf_modelo.setText(jtf_modelo.getText().toUpperCase());
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_modeloKeyReleased

    private void jft_anoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jft_anoKeyReleased
        jft_ano.setText(jft_ano.getText().toUpperCase());
        // TODO add your handling code here:
    }//GEN-LAST:event_jft_anoKeyReleased

    private void jtf_tipoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_tipoKeyReleased
        jtf_tipo.setText(jtf_tipo.getText().toUpperCase());
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_tipoKeyReleased

    private void jtf_chassiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_chassiActionPerformed
        jtf_chassi.setText(jtf_chassi.getText().toUpperCase());
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_chassiActionPerformed

    private void jtf_quilometragemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_quilometragemKeyReleased
        jtf_quilometragem.setText(jtf_quilometragem.getText().toUpperCase());
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_quilometragemKeyReleased

    private void jtf_chassiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_chassiKeyReleased
        jtf_chassi.setText(jtf_chassi.getText().toUpperCase());
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_chassiKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton jbn_cadastro;
    private javax.swing.JButton jbn_fechar;
    private javax.swing.JButton jbn_limpar;
    private javax.swing.JButton jbn_novo;
    private javax.swing.JFormattedTextField jft_ano;
    private javax.swing.JLabel jlb_ano;
    private javax.swing.JLabel jlb_chassi;
    private javax.swing.JLabel jlb_cor;
    private javax.swing.JLabel jlb_marca;
    private javax.swing.JLabel jlb_modelo;
    private javax.swing.JLabel jlb_placa;
    private javax.swing.JLabel jlb_quilometragem;
    private javax.swing.JLabel jlb_tipo;
    private javax.swing.JPanel jpl_opcoes;
    private javax.swing.JTextField jtf_alugado;
    private javax.swing.JTextField jtf_chassi;
    private javax.swing.JTextField jtf_cor1;
    private javax.swing.JTextField jtf_marca;
    private javax.swing.JTextField jtf_modelo;
    private javax.swing.JTextField jtf_placa;
    private javax.swing.JTextField jtf_quilometragem;
    private javax.swing.JTextField jtf_tipo;
    // End of variables declaration//GEN-END:variables
}
