/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Utilitarios.WebServiceCep;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import model.bean.Viagens;
import model.dao.ViagemDAO;

/**
 *
 * @author marcu
 */
public class jif_viagemBack extends javax.swing.JInternalFrame {

    /**
     * Creates new form jif_viagemBack
     */
    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    public void buscarInfo(String motorista, String cnh, String placa, String modelo, String id) {
        jtf_nomeMotorista.setText(motorista);
        jtf_cnh.setText(cnh);
        jtf_placa.setText(placa);
        jtf_modelo.setText(modelo);
        jtf_idveic.setText(id);

    }

    public jif_viagemBack() {

        
        initComponents();
        jtf_idveic.setVisible(false);

    }

    public void limpar() {
        jtf_cnh.setText("");
        jtf_endBairro.setText("");
        jtf_endCidade.setText("");
        jtf_endNum.setText("");
        jtf_endRua.setText("");
        jtf_endUF.setText("");
        jtf_kmSaida.setText("");
        jtf_modelo.setText("");
        jtf_nomeMotorista.setText("");
        jtf_placa.setText("");
        jtf_retornoKm.setText("");

        jft_dataSaida.setText("");
        jft_endCEP.setText("");
        jft_horaSaida.setText("");
        jft_retornoData.setText("");
        jft_retornoHora.setText("");

        jTextArea1.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jpl_opcoes = new javax.swing.JPanel();
        jbn_fechar = new javax.swing.JButton();
        jbn_limpar = new javax.swing.JButton();
        jbn_cadastro = new javax.swing.JButton();
        jbn_novo = new javax.swing.JButton();
        motVeicu = new javax.swing.JPanel();
        jlb_empresa2 = new javax.swing.JLabel();
        jlb_razaoSocial1 = new javax.swing.JLabel();
        jtf_placa = new javax.swing.JTextField();
        jtf_nomeMotorista = new javax.swing.JTextField();
        jlb_razaoSocial2 = new javax.swing.JLabel();
        jtf_modelo = new javax.swing.JTextField();
        jlb_razaoSocial3 = new javax.swing.JLabel();
        jtf_cnh = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jlb_cnpj = new javax.swing.JLabel();
        jft_horaSaida = new javax.swing.JFormattedTextField();
        jlb_cnpj1 = new javax.swing.JLabel();
        jft_dataSaida = new javax.swing.JFormattedTextField();
        jlb_cnpj2 = new javax.swing.JLabel();
        jtf_kmSaida = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jlb_cep = new javax.swing.JLabel();
        jft_endCEP = new javax.swing.JFormattedTextField();
        jtf_endUF = new javax.swing.JTextField();
        jlb_uf = new javax.swing.JLabel();
        jlb_cidade = new javax.swing.JLabel();
        jtf_endCidade = new javax.swing.JTextField();
        jlb_rua = new javax.swing.JLabel();
        jtf_endRua = new javax.swing.JTextField();
        jlb_numero = new javax.swing.JLabel();
        jtf_endNum = new javax.swing.JTextField();
        jtf_endBairro = new javax.swing.JTextField();
        jlb_bairro = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jlb_cnpj5 = new javax.swing.JLabel();
        jft_retornoHora = new javax.swing.JFormattedTextField();
        jlb_cnpj8 = new javax.swing.JLabel();
        jft_retornoData = new javax.swing.JFormattedTextField();
        jlb_cnpj9 = new javax.swing.JLabel();
        jtf_retornoKm = new javax.swing.JTextField();
        jtf_idveic = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Viagem"));

        jpl_opcoes.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jpl_opcoes.setToolTipText("Opções");

        jbn_fechar.setText("Fechar");
        jbn_fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_fecharActionPerformed(evt);
            }
        });

        jbn_limpar.setText("Limpar");
        jbn_limpar.setEnabled(false);
        jbn_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_limparActionPerformed(evt);
            }
        });

        jbn_cadastro.setText("Cadastrar");
        jbn_cadastro.setEnabled(false);
        jbn_cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_cadastroActionPerformed(evt);
            }
        });

        jbn_novo.setText("Novo");
        jbn_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_novoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpl_opcoesLayout = new javax.swing.GroupLayout(jpl_opcoes);
        jpl_opcoes.setLayout(jpl_opcoesLayout);
        jpl_opcoesLayout.setHorizontalGroup(
            jpl_opcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpl_opcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpl_opcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbn_fechar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbn_limpar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbn_novo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbn_cadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpl_opcoesLayout.setVerticalGroup(
            jpl_opcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpl_opcoesLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jbn_novo)
                .addGap(27, 27, 27)
                .addComponent(jbn_cadastro)
                .addGap(18, 18, 18)
                .addComponent(jbn_limpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                .addComponent(jbn_fechar)
                .addContainerGap())
        );

        motVeicu.setBorder(javax.swing.BorderFactory.createTitledBorder("Motorista e veiculo"));

        jlb_empresa2.setText("Motorista");

        jlb_razaoSocial1.setText("Placa:");

        jtf_placa.setEditable(false);
        jtf_placa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jtf_nomeMotorista.setEditable(false);
        jtf_nomeMotorista.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_nomeMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_nomeMotoristaActionPerformed(evt);
            }
        });
        jtf_nomeMotorista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_nomeMotoristaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_nomeMotoristaKeyTyped(evt);
            }
        });

        jlb_razaoSocial2.setText("Modelo:");

        jtf_modelo.setEditable(false);
        jtf_modelo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jlb_razaoSocial3.setText("CNH:");

        jtf_cnh.setEditable(false);
        jtf_cnh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout motVeicuLayout = new javax.swing.GroupLayout(motVeicu);
        motVeicu.setLayout(motVeicuLayout);
        motVeicuLayout.setHorizontalGroup(
            motVeicuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(motVeicuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(motVeicuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(motVeicuLayout.createSequentialGroup()
                        .addComponent(jlb_empresa2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtf_nomeMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, motVeicuLayout.createSequentialGroup()
                        .addComponent(jlb_razaoSocial3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_cnh, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(jlb_razaoSocial1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_placa, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlb_razaoSocial2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        motVeicuLayout.setVerticalGroup(
            motVeicuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, motVeicuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(motVeicuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_nomeMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlb_empresa2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(motVeicuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(motVeicuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtf_cnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlb_razaoSocial3))
                    .addGroup(motVeicuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtf_placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlb_razaoSocial1))
                    .addGroup(motVeicuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtf_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlb_razaoSocial2)))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Inicio viagem"));

        jlb_cnpj.setText("Hora:");

        try {
            jft_horaSaida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jft_horaSaida.setEnabled(false);
        jft_horaSaida.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jft_horaSaida.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jft_horaSaidaFocusLost(evt);
            }
        });
        jft_horaSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jft_horaSaidaActionPerformed(evt);
            }
        });

        jlb_cnpj1.setText("Data:");

        try {
            jft_dataSaida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jft_dataSaida.setEnabled(false);
        jft_dataSaida.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jft_dataSaida.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jft_dataSaidaFocusLost(evt);
            }
        });
        jft_dataSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jft_dataSaidaActionPerformed(evt);
            }
        });

        jlb_cnpj2.setText("KM:");

        jtf_kmSaida.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_kmSaida.setEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jlb_cnpj2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtf_kmSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jlb_cnpj)
                        .addGap(18, 18, 18)
                        .addComponent(jft_horaSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlb_cnpj1)
                        .addGap(18, 18, 18)
                        .addComponent(jft_dataSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jft_horaSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlb_cnpj)
                    .addComponent(jft_dataSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlb_cnpj1))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_cnpj2)
                    .addComponent(jtf_kmSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));

        jlb_cep.setText("CEP:");

        try {
            jft_endCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jft_endCEP.setEnabled(false);
        jft_endCEP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jft_endCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jft_endCEPActionPerformed(evt);
            }
        });
        jft_endCEP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jft_endCEPKeyReleased(evt);
            }
        });

        jtf_endUF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_endUF.setEnabled(false);

        jlb_uf.setText("UF:");

        jlb_cidade.setText("Cidade:");

        jtf_endCidade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_endCidade.setEnabled(false);

        jlb_rua.setText("Rua:");

        jtf_endRua.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_endRua.setEnabled(false);

        jlb_numero.setText("Nº:");

        jtf_endNum.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_endNum.setEnabled(false);

        jtf_endBairro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_endBairro.setEnabled(false);

        jlb_bairro.setText("Bairro:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jlb_numero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtf_endNum, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlb_bairro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_endBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jlb_cep)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jft_endCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jlb_uf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_endUF, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlb_cidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtf_endCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jlb_rua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_endRua, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_cep)
                    .addComponent(jft_endCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlb_uf)
                    .addComponent(jtf_endUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlb_cidade)
                    .addComponent(jtf_endCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_rua)
                    .addComponent(jtf_endRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_numero)
                    .addComponent(jtf_endNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlb_bairro)
                    .addComponent(jtf_endBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Retorno"));

        jlb_cnpj5.setText("Hora:");

        try {
            jft_retornoHora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jft_retornoHora.setEnabled(false);
        jft_retornoHora.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jft_retornoHora.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jft_retornoHoraFocusLost(evt);
            }
        });
        jft_retornoHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jft_retornoHoraActionPerformed(evt);
            }
        });

        jlb_cnpj8.setText("Data:");

        try {
            jft_retornoData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jft_retornoData.setEnabled(false);
        jft_retornoData.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jft_retornoData.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jft_retornoDataFocusLost(evt);
            }
        });
        jft_retornoData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jft_retornoDataActionPerformed(evt);
            }
        });

        jlb_cnpj9.setText("KM:");

        jtf_retornoKm.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_retornoKm.setEnabled(false);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jlb_cnpj9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtf_retornoKm, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtf_idveic, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jlb_cnpj5)
                        .addGap(18, 18, 18)
                        .addComponent(jft_retornoHora, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlb_cnpj8)
                        .addGap(18, 18, 18)
                        .addComponent(jft_retornoData, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jft_retornoHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlb_cnpj5)
                    .addComponent(jft_retornoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlb_cnpj8))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_cnpj9)
                    .addComponent(jtf_retornoKm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_idveic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Motivo"));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(motVeicu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(5, 5, 5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jpl_opcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpl_opcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(motVeicu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbn_fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_fecharActionPerformed

        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jbn_fecharActionPerformed

    private void jbn_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_limparActionPerformed
        limpar();
        // TODO add your handling code here:
    }//GEN-LAST:event_jbn_limparActionPerformed

    private void jbn_cadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_cadastroActionPerformed
        Viagens v = new Viagens();
        ViagemDAO vd;

        vd = new ViagemDAO();
        v.setDataViagem(jft_dataSaida.getText());
        v.setBairro(jtf_endBairro.getText());
        v.setCep(jft_endCEP.getText());
        v.setCidade(jtf_endCidade.getText());
        v.setHoraFinal(jft_retornoHora.getText());
        v.setHoraInicio(jft_horaSaida.getText());
        v.setHoraRetorno(jft_retornoHora.getText());
        v.setKmFinal(Integer.parseInt(jtf_retornoKm.getText()));
        v.setKmInicial(Integer.parseInt(jtf_kmSaida.getText()));
        v.setMotivo(jTextArea1.getText());
        v.setNumero(Integer.parseInt(jtf_endNum.getText()));
        v.setRua(jtf_endRua.getText());
        v.setUf(jtf_endUF.getText());
        v.setIdVeic(Integer.parseInt(jtf_idveic.getText()));
        vd.inserir(v);
        limpar();

        //JOptionPane.showMessageDialog(null, "Inserido com sucesso!");
    }//GEN-LAST:event_jbn_cadastroActionPerformed

    private void jbn_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_novoActionPerformed
        jbn_cadastro.setEnabled(true);
        jbn_limpar.setEnabled(true);

        jtf_endRua.setEnabled(true);
        jft_endCEP.setEnabled(true);
        jtf_endBairro.setEnabled(true);
        jtf_endNum.setEnabled(true);

        jtf_endCidade.setEnabled(true);

        jft_dataSaida.setEnabled(true);
        jft_endCEP.setEnabled(true);
        jft_horaSaida.setEnabled(true);
        jft_retornoData.setEnabled(true);
        jft_retornoHora.setEnabled(true);

        jtf_endUF.setEnabled(true);
        jtf_retornoKm.setEnabled(true);

        jtf_kmSaida.setEnabled(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jbn_novoActionPerformed

    private void jft_horaSaidaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jft_horaSaidaFocusLost

        // TODO add your handling code here:
    }//GEN-LAST:event_jft_horaSaidaFocusLost

    private void jft_endCEPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jft_endCEPKeyReleased
        String cp = jft_endCEP.getText();
        cp = cp.replaceAll("\\D*", ""); //ignora qualquer coisa que não seja numero.  
        int cont = cp.length();

        if (cont == 8) {
            try {
                correio();
            } catch (Error e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jft_endCEPKeyReleased

    private void jtf_nomeMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_nomeMotoristaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_nomeMotoristaActionPerformed

    private void jtf_nomeMotoristaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_nomeMotoristaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_nomeMotoristaKeyReleased

    private void jtf_nomeMotoristaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_nomeMotoristaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_nomeMotoristaKeyTyped

    private void jft_horaSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jft_horaSaidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jft_horaSaidaActionPerformed

    private void jft_dataSaidaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jft_dataSaidaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jft_dataSaidaFocusLost

    private void jft_dataSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jft_dataSaidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jft_dataSaidaActionPerformed

    private void jft_endCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jft_endCEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jft_endCEPActionPerformed

    private void jft_retornoHoraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jft_retornoHoraFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jft_retornoHoraFocusLost

    private void jft_retornoHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jft_retornoHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jft_retornoHoraActionPerformed

    private void jft_retornoDataFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jft_retornoDataFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jft_retornoDataFocusLost

    private void jft_retornoDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jft_retornoDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jft_retornoDataActionPerformed

    public void correio() {

        String cep = jft_endCEP.getText();

        WebServiceCep webServiceCep = WebServiceCep.searchCep(cep);

        if (webServiceCep.wasSuccessful()) {

            jtf_endRua.setText(webServiceCep.getLogradouroFull().toUpperCase());
            jtf_endBairro.setText(webServiceCep.getBairro().toUpperCase());
            jtf_endCidade.setText(webServiceCep.getCidade().toUpperCase());
            jtf_endUF.setText(webServiceCep.getUf().toUpperCase());

        } else {
            JOptionPane.showMessageDialog(null, webServiceCep.getResultText());

        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jbn_cadastro;
    private javax.swing.JButton jbn_fechar;
    private javax.swing.JButton jbn_limpar;
    private javax.swing.JButton jbn_novo;
    private javax.swing.JFormattedTextField jft_dataSaida;
    private javax.swing.JFormattedTextField jft_endCEP;
    private javax.swing.JFormattedTextField jft_horaSaida;
    private javax.swing.JFormattedTextField jft_retornoData;
    private javax.swing.JFormattedTextField jft_retornoHora;
    private javax.swing.JLabel jlb_bairro;
    private javax.swing.JLabel jlb_cep;
    private javax.swing.JLabel jlb_cidade;
    private javax.swing.JLabel jlb_cnpj;
    private javax.swing.JLabel jlb_cnpj1;
    private javax.swing.JLabel jlb_cnpj2;
    private javax.swing.JLabel jlb_cnpj5;
    private javax.swing.JLabel jlb_cnpj8;
    private javax.swing.JLabel jlb_cnpj9;
    private javax.swing.JLabel jlb_empresa2;
    private javax.swing.JLabel jlb_numero;
    private javax.swing.JLabel jlb_razaoSocial1;
    private javax.swing.JLabel jlb_razaoSocial2;
    private javax.swing.JLabel jlb_razaoSocial3;
    private javax.swing.JLabel jlb_rua;
    private javax.swing.JLabel jlb_uf;
    private javax.swing.JPanel jpl_opcoes;
    private javax.swing.JTextField jtf_cnh;
    private javax.swing.JTextField jtf_endBairro;
    private javax.swing.JTextField jtf_endCidade;
    private javax.swing.JTextField jtf_endNum;
    private javax.swing.JTextField jtf_endRua;
    private javax.swing.JTextField jtf_endUF;
    private javax.swing.JTextField jtf_idveic;
    private javax.swing.JTextField jtf_kmSaida;
    private javax.swing.JTextField jtf_modelo;
    private javax.swing.JTextField jtf_nomeMotorista;
    private javax.swing.JTextField jtf_placa;
    private javax.swing.JTextField jtf_retornoKm;
    private javax.swing.JPanel motVeicu;
    // End of variables declaration//GEN-END:variables
}
