package view;

import Utilitarios.WebServiceCep;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.bean.Multa;
import model.bean.Veiculo;
import model.dao.MultaDAO;
import model.dao.VeiculoDAO;

/**
 *
 * @author total
 */
public class jif_multa extends javax.swing.JInternalFrame {

    /**
     * Creates new form jif_manutencao
     */
    public boolean verifica() {
        if (jtf_valor.getText().equals("")) {
            return false;

        }
        if (jta_obs.getText().equals("")) {
            return false;

        }
        if (jtf_gravidade.getText().equals("")) {
            return false;
        }
        if (jft_data.getText().equals("  /  /    ")) {
            return false;
        }

        if (jft_pontuacao.getText().equals("")) {
            return false;
        } else {
            return true;
        }
    }

    public void limpar() {
        jta_obs.setText("");
        jtf_valor.setText("");
        jtf_gravidade.setText("");
        jtf_endBairro.setText("");
        jtf_endCidade.setText("");
        jtf_endNum.setText("");
        jtf_endRua.setText("");
        jtf_endUF.setText("");
        jtf_idveic.setText("");
        jtf_infracao.setText("");
        jtf_placa.setText("");
        jft_data.setText("");
        jft_dataNot.setText("");
        jft_dataVen.setText("");
        jft_endCEP.setText("");
        jft_pontuacao.setText("");
        jta_obs.setText("");
        jft_pontuacao.setText("");
    }

    public void novo(boolean op) {

        jtf_valor.setEnabled(op);
        jtf_gravidade.setEnabled(op);
        jtf_endBairro.setEnabled(op);
        jtf_endCidade.setEnabled(op);
        jtf_endNum.setEnabled(op);
        jtf_endRua.setEnabled(op);
        jtf_endUF.setEnabled(op);
        jtf_idveic.setEnabled(op);
        jtf_infracao.setEnabled(op);

        jft_data.setEnabled(op);
        jft_dataNot.setEnabled(op);
        jft_dataVen.setEnabled(op);
        jft_endCEP.setEnabled(op);
        jft_pontuacao.setEnabled(op);
        jta_obs.setEnabled(op);
        jft_pontuacao.setEnabled(op);
        jcb_situacao.setEnabled(op);
        jbn_cadastro.setEnabled(op);
        jbn_limpar.setEnabled(op);

    }

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    public jif_multa() {
        initComponents();
        jtf_idveic.setVisible(false);
    }

    public void ChamaModelo() {
        Veiculo v = new Veiculo();
        v.setPlaca(jtf_placa.getText());
        String retorno2 = "";
        try {
            VeiculoDAO vd = new VeiculoDAO();

            retorno2 = vd.BuscarVeic2(v.getPlaca());

        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(jif_cadastroVeiculo.class.getName()).log(Level.SEVERE, null, ex);
        }
        //jtf_idPlaca.setText(String.valueOf(retorno));

        jtf_modelo.setText(retorno2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jpl_opcoes3 = new javax.swing.JPanel();
        jbn_fechar3 = new javax.swing.JButton();
        jbn_limpar = new javax.swing.JButton();
        jbn_cadastro = new javax.swing.JButton();
        jbn_novo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtf_placa = new javax.swing.JTextField();
        jbn_buscar = new javax.swing.JButton();
        jtf_idveic = new javax.swing.JTextField();
        jtf_modelo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtf_gravidade = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jft_data = new javax.swing.JFormattedTextField();
        jtf_valor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta_obs = new javax.swing.JTextArea();
        jft_pontuacao = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtf_infracao = new javax.swing.JTextField();
        jlb_cep = new javax.swing.JLabel();
        jft_endCEP = new javax.swing.JFormattedTextField();
        jlb_uf = new javax.swing.JLabel();
        jtf_endUF = new javax.swing.JTextField();
        jlb_cidade = new javax.swing.JLabel();
        jtf_endCidade = new javax.swing.JTextField();
        jtf_endRua = new javax.swing.JTextField();
        jlb_rua = new javax.swing.JLabel();
        jlb_numero = new javax.swing.JLabel();
        jtf_endNum = new javax.swing.JTextField();
        jtf_endBairro = new javax.swing.JTextField();
        jlb_bairro = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jft_dataNot = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jft_dataVen = new javax.swing.JFormattedTextField();
        jcb_situacao = new javax.swing.JComboBox<>();
        jlb_bairro1 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Multa"));

        jpl_opcoes3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jpl_opcoes3.setToolTipText("Opções");

        jbn_fechar3.setText("Fechar");
        jbn_fechar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_fechar3ActionPerformed(evt);
            }
        });

        jbn_limpar.setText("Limpar");
        jbn_limpar.setEnabled(false);
        jbn_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_limparActionPerformed(evt);
            }
        });

        jbn_cadastro.setText("Cadastrar");
        jbn_cadastro.setEnabled(false);
        jbn_cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_cadastroActionPerformed(evt);
            }
        });

        jbn_novo.setText("Novo");
        jbn_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_novoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpl_opcoes3Layout = new javax.swing.GroupLayout(jpl_opcoes3);
        jpl_opcoes3.setLayout(jpl_opcoes3Layout);
        jpl_opcoes3Layout.setHorizontalGroup(
            jpl_opcoes3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpl_opcoes3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpl_opcoes3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbn_fechar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbn_limpar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbn_novo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbn_cadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpl_opcoes3Layout.setVerticalGroup(
            jpl_opcoes3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpl_opcoes3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jbn_novo)
                .addGap(27, 27, 27)
                .addComponent(jbn_cadastro)
                .addGap(18, 18, 18)
                .addComponent(jbn_limpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbn_fechar3)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Veiculo"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Placa:");

        jtf_placa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_placa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_placaKeyReleased(evt);
            }
        });

        jbn_buscar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbn_buscar.setText("Buscar");
        jbn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_buscarActionPerformed(evt);
            }
        });

        jtf_modelo.setEditable(false);
        jtf_modelo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_placa, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbn_buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_idveic, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtf_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jbn_buscar)
                    .addComponent(jtf_idveic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Gravidade:");

        jtf_gravidade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_gravidade.setEnabled(false);
        jtf_gravidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_gravidadeKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Pontuação:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Data:");

        try {
            jft_data.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jft_data.setEnabled(false);
        jft_data.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jtf_valor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_valor.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Valor:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Observação:");

        jta_obs.setColumns(20);
        jta_obs.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jta_obs.setRows(5);
        jta_obs.setEnabled(false);
        jta_obs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jta_obsKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jta_obs);

        jft_pontuacao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jft_pontuacao.setEnabled(false);
        jft_pontuacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jft_pontuacaoKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Infração:");

        jtf_infracao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_infracao.setEnabled(false);
        jtf_infracao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_infracaoKeyReleased(evt);
            }
        });

        jlb_cep.setText("CEP:");

        try {
            jft_endCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jft_endCEP.setEnabled(false);
        jft_endCEP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jft_endCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jft_endCEPActionPerformed(evt);
            }
        });
        jft_endCEP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jft_endCEPKeyReleased(evt);
            }
        });

        jlb_uf.setText("UF:");

        jtf_endUF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_endUF.setEnabled(false);
        jtf_endUF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_endUFKeyReleased(evt);
            }
        });

        jlb_cidade.setText("Cidade:");

        jtf_endCidade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_endCidade.setEnabled(false);
        jtf_endCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_endCidadeKeyReleased(evt);
            }
        });

        jtf_endRua.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_endRua.setEnabled(false);
        jtf_endRua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_endRuaKeyReleased(evt);
            }
        });

        jlb_rua.setText("Rua:");

        jlb_numero.setText("Nº aproximado:");

        jtf_endNum.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_endNum.setEnabled(false);

        jtf_endBairro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf_endBairro.setEnabled(false);
        jtf_endBairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_endBairroKeyReleased(evt);
            }
        });

        jlb_bairro.setText("Bairro:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Data notificação:");

        try {
            jft_dataNot.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jft_dataNot.setEnabled(false);
        jft_dataNot.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Data vencimento:");

        try {
            jft_dataVen.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jft_dataVen.setEnabled(false);
        jft_dataVen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jcb_situacao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcb_situacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "PROCESSO", "PENDENTE", "PAGO" }));
        jcb_situacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_situacaoActionPerformed(evt);
            }
        });

        jlb_bairro1.setText("Situação:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jft_data, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jft_pontuacao, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_gravidade, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_infracao, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jft_dataNot, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jft_dataVen, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtf_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlb_cep)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jft_endCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jlb_uf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_endUF, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jlb_cidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_endCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlb_rua)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_endRua, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlb_numero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtf_endNum, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jlb_bairro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_endBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlb_bairro1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcb_situacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpl_opcoes3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jft_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jft_pontuacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_gravidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtf_infracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jtf_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jft_dataNot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jft_dataVen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlb_cep)
                            .addComponent(jft_endCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlb_uf)
                            .addComponent(jtf_endUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlb_cidade)
                            .addComponent(jtf_endCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtf_endRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlb_rua))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlb_numero)
                            .addComponent(jtf_endNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlb_bairro)
                            .addComponent(jtf_endBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcb_situacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlb_bairro1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jpl_opcoes3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbn_fechar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_fechar3ActionPerformed

        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jbn_fechar3ActionPerformed

    private void jbn_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_limparActionPerformed
        limpar();
        // TODO add your handling code here:Su
    }//GEN-LAST:event_jbn_limparActionPerformed

    private void jbn_cadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_cadastroActionPerformed
        Multa m = new Multa();
        MultaDAO md;

        try {
            md = new MultaDAO();
            m.setBairro(jtf_endBairro.getText());
            m.setCep(jft_endCEP.getText());
            m.setCidade(jtf_endCidade.getText());
            m.setDataNotificacao(jft_dataNot.getText());
            m.setDataOcorrencia(jft_data.getText());
            m.setDataVencimento(jft_dataVen.getText());
            m.setGravidade(jtf_gravidade.getText());
            m.setIdVeic(Integer.parseInt(jtf_idveic.getText()));
            m.setInfracao(jtf_infracao.getText());
            m.setNumero(Integer.parseInt(jtf_endNum.getText()));
            m.setObervacao(jta_obs.getText());
            m.setPotuacao(jft_pontuacao.getText());
            m.setRua(jtf_endRua.getText());
            m.setUf(jtf_endUF.getText());
            m.setValor(Float.parseFloat(jtf_valor.getText()));
            m.setSituacao(String.valueOf(jcb_situacao.getSelectedItem()));
            md.inserir(m);
            limpar();

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(jif_seguro.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jbn_cadastroActionPerformed

    private void jbn_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_novoActionPerformed

        novo(false);
        jtf_placa.setText("");
        jtf_placa.setEditable(true);
        jbn_buscar.setEnabled(true);
        jtf_modelo.setText("");
        limpar();

        // TODO add your handling code here:
    }//GEN-LAST:event_jbn_novoActionPerformed

    private void jbn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_buscarActionPerformed
        Veiculo v = new Veiculo();
        v.setPlaca(jtf_placa.getText());

        int retorno = 0;

        try {
            VeiculoDAO vd = new VeiculoDAO();
            retorno = vd.BuscarVeicAlugado(v.getPlaca());
            if (retorno > 0) {
                novo(true);
                jtf_placa.setEditable(false);
                jbn_buscar.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(null, "Placa incorreta!!!", "ATENÇÃO!!!", JOptionPane.WARNING_MESSAGE);
            }

        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(jif_cadastroVeiculo.class.getName()).log(Level.SEVERE, null, ex);
        }
        //jtf_idPlaca.setText(String.valueOf(retorno));
        System.out.println("pega -> " + retorno);
        jtf_idveic.setText(String.valueOf(retorno));
        ChamaModelo();
        // TODO add your handling code here:
    }//GEN-LAST:event_jbn_buscarActionPerformed

    private void jft_endCEPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jft_endCEPKeyReleased
        String cp = jft_endCEP.getText();
        cp = cp.replaceAll("\\D*", ""); //ignora qualquer coisa que não seja numero.
        int cont = cp.length();

        if (cont == 8) {
            try {
                correio();
            } catch (Error e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jft_endCEPKeyReleased

    private void jft_endCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jft_endCEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jft_endCEPActionPerformed

    private void jft_pontuacaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jft_pontuacaoKeyReleased
        jft_pontuacao.setText(jft_pontuacao.getText().toUpperCase());
        // TODO add your handling code here:
    }//GEN-LAST:event_jft_pontuacaoKeyReleased

    private void jtf_gravidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_gravidadeKeyReleased
        jtf_gravidade.setText(jtf_gravidade.getText().toUpperCase());
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_gravidadeKeyReleased

    private void jtf_infracaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_infracaoKeyReleased
        jtf_infracao.setText(jtf_infracao.getText().toUpperCase());
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_infracaoKeyReleased

    private void jta_obsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jta_obsKeyReleased
        jta_obs.setText(jta_obs.getText().toUpperCase());
        // TODO add your handling code here:
    }//GEN-LAST:event_jta_obsKeyReleased

    private void jcb_situacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_situacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_situacaoActionPerformed

    private void jtf_endBairroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_endBairroKeyReleased
        jtf_endBairro.setText(jtf_endBairro.getText().toUpperCase());
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_endBairroKeyReleased

    private void jtf_endRuaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_endRuaKeyReleased
        jtf_endRua.setText(jtf_endRua.getText().toUpperCase());
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_endRuaKeyReleased

    private void jtf_endCidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_endCidadeKeyReleased
        jtf_endCidade.setText(jtf_endCidade.getText().toUpperCase());
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_endCidadeKeyReleased

    private void jtf_endUFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_endUFKeyReleased
        jtf_endUF.setText(jtf_endUF.getText().toUpperCase());
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_endUFKeyReleased

    private void jtf_placaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_placaKeyReleased
        jtf_placa.setText(jtf_placa.getText().toUpperCase());
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_placaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbn_buscar;
    private javax.swing.JButton jbn_cadastro;
    private javax.swing.JButton jbn_fechar3;
    private javax.swing.JButton jbn_limpar;
    private javax.swing.JButton jbn_novo;
    private javax.swing.JComboBox<String> jcb_situacao;
    private javax.swing.JFormattedTextField jft_data;
    private javax.swing.JFormattedTextField jft_dataNot;
    private javax.swing.JFormattedTextField jft_dataVen;
    private javax.swing.JFormattedTextField jft_endCEP;
    private javax.swing.JTextField jft_pontuacao;
    private javax.swing.JLabel jlb_bairro;
    private javax.swing.JLabel jlb_bairro1;
    private javax.swing.JLabel jlb_cep;
    private javax.swing.JLabel jlb_cidade;
    private javax.swing.JLabel jlb_numero;
    private javax.swing.JLabel jlb_rua;
    private javax.swing.JLabel jlb_uf;
    private javax.swing.JPanel jpl_opcoes3;
    private javax.swing.JTextArea jta_obs;
    private javax.swing.JTextField jtf_endBairro;
    private javax.swing.JTextField jtf_endCidade;
    private javax.swing.JTextField jtf_endNum;
    private javax.swing.JTextField jtf_endRua;
    private javax.swing.JTextField jtf_endUF;
    private javax.swing.JTextField jtf_gravidade;
    private javax.swing.JTextField jtf_idveic;
    private javax.swing.JTextField jtf_infracao;
    private javax.swing.JTextField jtf_modelo;
    private javax.swing.JTextField jtf_placa;
    private javax.swing.JTextField jtf_valor;
    // End of variables declaration//GEN-END:variables
public void correio() {

        String cep = jft_endCEP.getText();

        WebServiceCep webServiceCep = WebServiceCep.searchCep(cep);

        if (webServiceCep.wasSuccessful()) {

            jtf_endRua.setText(webServiceCep.getLogradouroFull().toUpperCase());
            jtf_endBairro.setText(webServiceCep.getBairro().toUpperCase());
            jtf_endCidade.setText(webServiceCep.getCidade().toUpperCase());
            jtf_endUF.setText(webServiceCep.getUf().toUpperCase());

        } else {
            JOptionPane.showMessageDialog(null, webServiceCep.getResultText());

        }

    }

}
