package view;


import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import view.jif_abastecimento;
import view.jif_cadastroAluguel;
import view.jif_cadastroCliente;
import view.jif_cadastroMotorista;
import view.jif_cadastroVeiculo;
import view.jif_consultaCliente;

import view.jif_consultaMotorista;
import view.jif_consultaVeiculo;
import view.jif_multa;
import view.jif_pneu;
import view.jif_seguro;
import view.jif_viagemBack;
import view.jif_viagemFront;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author total
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    

    
    public Main() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }
   // jif_viagemBack viagem1 = new jif_viagemBack();
    public void viagem(){
         jif_viagemBack viagem1 = new jif_viagemBack();
        desktopPane.add(viagem1);
        viagem1.setPosicao();
        ((BasicInternalFrameUI)viagem1.getUI()).setNorthPane(null);
        //viagem1.setVisible(false); 
        viagem1.setVisible(true); 
       
    }
    
    public void acesso(int i){
        if(i == 1){
            CadastroMenu.setEnabled(true);
            SolicitaMenu.setEnabled(true);
            ConsultaMenu.setEnabled(true);
            Cad_aluguel.setEnabled(true);
            }
        else if( i == 2){
            CadastroMenu.setEnabled(true);
            SolicitaMenu.setEnabled(true);
            ConsultaMenu.setEnabled(true);
            Cad_cliente.setEnabled(false);
            consultaCliente.setEnabled(false);
        }else{
            
            
            ConsultaMenu.setEnabled(true);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        CadastroMenu = new javax.swing.JMenu();
        Cad_cliente = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Cad_motorista = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        Cad_veiculo = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        Cad_aluguel = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        Cad_pneu = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        Cad_multa = new javax.swing.JMenuItem();
        jSeparator12 = new javax.swing.JPopupMenu.Separator();
        Cad_abastecimento = new javax.swing.JMenuItem();
        jSeparator13 = new javax.swing.JPopupMenu.Separator();
        Cad_seguro = new javax.swing.JMenuItem();
        SolicitaMenu = new javax.swing.JMenu();
        solicitaViagem = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        solicitaManutencao = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        ConsultaMenu = new javax.swing.JMenu();
        consultaMotorista = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        consultaCliente = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        consultaVeiculo = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CadastroMenu.setMnemonic('f');
        CadastroMenu.setText("Cadastro");
        CadastroMenu.setEnabled(false);

        Cad_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/cliente.png"))); // NOI18N
        Cad_cliente.setMnemonic('o');
        Cad_cliente.setText("Cliente");
        Cad_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cad_clienteActionPerformed(evt);
            }
        });
        CadastroMenu.add(Cad_cliente);
        CadastroMenu.add(jSeparator1);

        Cad_motorista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/motorista.png"))); // NOI18N
        Cad_motorista.setMnemonic('s');
        Cad_motorista.setText("Motorista");
        Cad_motorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cad_motoristaActionPerformed(evt);
            }
        });
        CadastroMenu.add(Cad_motorista);
        CadastroMenu.add(jSeparator3);

        Cad_veiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/carro.png"))); // NOI18N
        Cad_veiculo.setMnemonic('a');
        Cad_veiculo.setText("Veiculo");
        Cad_veiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cad_veiculoActionPerformed(evt);
            }
        });
        CadastroMenu.add(Cad_veiculo);
        CadastroMenu.add(jSeparator2);

        Cad_aluguel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/carroAluguel.png"))); // NOI18N
        Cad_aluguel.setText("Veiculo aluguel");
        Cad_aluguel.setEnabled(false);
        Cad_aluguel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cad_aluguelActionPerformed(evt);
            }
        });
        CadastroMenu.add(Cad_aluguel);
        CadastroMenu.add(jSeparator10);

        Cad_pneu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/iconfinder_tire_172600.png"))); // NOI18N
        Cad_pneu.setText("Pneu");
        Cad_pneu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cad_pneuActionPerformed(evt);
            }
        });
        CadastroMenu.add(Cad_pneu);
        CadastroMenu.add(jSeparator11);

        Cad_multa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/multa.png"))); // NOI18N
        Cad_multa.setText("Multa");
        Cad_multa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cad_multaActionPerformed(evt);
            }
        });
        CadastroMenu.add(Cad_multa);
        CadastroMenu.add(jSeparator12);

        Cad_abastecimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/gas.png"))); // NOI18N
        Cad_abastecimento.setText("Abastecimento");
        Cad_abastecimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cad_abastecimentoActionPerformed(evt);
            }
        });
        CadastroMenu.add(Cad_abastecimento);
        CadastroMenu.add(jSeparator13);

        Cad_seguro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/safe.png"))); // NOI18N
        Cad_seguro.setText("Seguro");
        Cad_seguro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cad_seguroActionPerformed(evt);
            }
        });
        CadastroMenu.add(Cad_seguro);

        menuBar.add(CadastroMenu);

        SolicitaMenu.setMnemonic('h');
        SolicitaMenu.setText("Solicita");
        SolicitaMenu.setEnabled(false);

        solicitaViagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/viagem.png"))); // NOI18N
        solicitaViagem.setMnemonic('c');
        solicitaViagem.setText("Viagem");
        solicitaViagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solicitaViagemActionPerformed(evt);
            }
        });
        SolicitaMenu.add(solicitaViagem);
        SolicitaMenu.add(jSeparator4);

        solicitaManutencao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/manutencao.png"))); // NOI18N
        solicitaManutencao.setMnemonic('a');
        solicitaManutencao.setText("Manutençao");
        solicitaManutencao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solicitaManutencaoActionPerformed(evt);
            }
        });
        SolicitaMenu.add(solicitaManutencao);
        SolicitaMenu.add(jSeparator9);

        menuBar.add(SolicitaMenu);

        ConsultaMenu.setMnemonic('e');
        ConsultaMenu.setText("Consulta");
        ConsultaMenu.setEnabled(false);

        consultaMotorista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/motorista.png"))); // NOI18N
        consultaMotorista.setMnemonic('t');
        consultaMotorista.setText("Motorista");
        consultaMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaMotoristaActionPerformed(evt);
            }
        });
        ConsultaMenu.add(consultaMotorista);
        ConsultaMenu.add(jSeparator7);

        consultaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/cliente.png"))); // NOI18N
        consultaCliente.setMnemonic('y');
        consultaCliente.setText("Cliente");
        consultaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaClienteActionPerformed(evt);
            }
        });
        ConsultaMenu.add(consultaCliente);
        ConsultaMenu.add(jSeparator6);

        consultaVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/carro.png"))); // NOI18N
        consultaVeiculo.setMnemonic('p');
        consultaVeiculo.setText("Veiculo");
        consultaVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaVeiculoActionPerformed(evt);
            }
        });
        ConsultaMenu.add(consultaVeiculo);
        ConsultaMenu.add(jSeparator5);

        menuBar.add(ConsultaMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Cad_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cad_clienteActionPerformed
        jif_cadastroCliente cliente = new jif_cadastroCliente();
        desktopPane.add(cliente);
        cliente.setPosicao();
        ((BasicInternalFrameUI)cliente.getUI()).setNorthPane(null);
        cliente.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_Cad_clienteActionPerformed

    private void Cad_motoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cad_motoristaActionPerformed
        jif_cadastroMotorista motorista = new jif_cadastroMotorista();
        desktopPane.add(motorista);
        motorista.setPosicao();
        ((BasicInternalFrameUI)motorista.getUI()).setNorthPane(null);
        motorista.setVisible(true);        
// TODO add your handling code here:
    }//GEN-LAST:event_Cad_motoristaActionPerformed

    private void Cad_veiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cad_veiculoActionPerformed
        jif_cadastroVeiculo veiculo = new jif_cadastroVeiculo();
        desktopPane.add(veiculo);
        veiculo.setPosicao();
        ((BasicInternalFrameUI)veiculo.getUI()).setNorthPane(null);
        veiculo.setVisible(true); 
// TODO add your handling code here:
    }//GEN-LAST:event_Cad_veiculoActionPerformed

    private void consultaVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaVeiculoActionPerformed
        jif_consultaVeiculo veiculo = null;
        try {
            veiculo = new jif_consultaVeiculo();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        desktopPane.add(veiculo);
        veiculo.setPosicao();
        ((BasicInternalFrameUI)veiculo.getUI()).setNorthPane(null);
        veiculo.setVisible(true); 
        // TODO add your handling code here:
    }//GEN-LAST:event_consultaVeiculoActionPerformed

    private void consultaMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaMotoristaActionPerformed
        jif_consultaMotorista motorista = null;
        try {
            motorista = new jif_consultaMotorista();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        desktopPane.add(motorista);
        motorista.setPosicao();
        ((BasicInternalFrameUI)motorista.getUI()).setNorthPane(null);
        motorista.setVisible(true); 
// TODO add your handling code here:
    }//GEN-LAST:event_consultaMotoristaActionPerformed

    private void consultaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaClienteActionPerformed
        jif_consultaCliente cliente = null;
        try {
            cliente = new jif_consultaCliente();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        desktopPane.add(cliente);
        cliente.setPosicao();
        ((BasicInternalFrameUI)cliente.getUI()).setNorthPane(null);
        cliente.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_consultaClienteActionPerformed

    private void Cad_aluguelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cad_aluguelActionPerformed
        jif_cadastroAluguel alug = new jif_cadastroAluguel();
        desktopPane.add(alug);
        alug.setPosicao();
        ((BasicInternalFrameUI)alug.getUI()).setNorthPane(null);
        alug.setVisible(true); 

// TODO add your handling code here:
    }//GEN-LAST:event_Cad_aluguelActionPerformed

    private void solicitaViagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solicitaViagemActionPerformed
        // TODO add your handling code here:
         jif_viagemFront viagem = new jif_viagemFront();
        desktopPane.add(viagem);
        viagem.setPosicao();
        ((BasicInternalFrameUI)viagem.getUI()).setNorthPane(null);
        viagem.setVisible(true); 
       
       
    }//GEN-LAST:event_solicitaViagemActionPerformed

    private void solicitaManutencaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solicitaManutencaoActionPerformed
         jif_manutencao manu = new jif_manutencao();
        desktopPane.add(manu);
        manu.setPosicao();
        ((BasicInternalFrameUI)manu.getUI()).setNorthPane(null);
        manu.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_solicitaManutencaoActionPerformed

    private void Cad_pneuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cad_pneuActionPerformed
       jif_pneu pneu = new jif_pneu();
        desktopPane.add(pneu);
        pneu.setPosicao();
        ((BasicInternalFrameUI)pneu.getUI()).setNorthPane(null);
        pneu.setVisible(true);
        
// TODO add your handling code here:
    }//GEN-LAST:event_Cad_pneuActionPerformed

    private void Cad_abastecimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cad_abastecimentoActionPerformed
        // TODO add your handling code here:
        jif_abastecimento abastecimento = new jif_abastecimento();
        desktopPane.add(abastecimento);
        abastecimento.setPosicao();
        ((BasicInternalFrameUI)abastecimento.getUI()).setNorthPane(null);
        abastecimento.setVisible(true);
    }//GEN-LAST:event_Cad_abastecimentoActionPerformed

    private void Cad_seguroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cad_seguroActionPerformed
        // TODO add your handling code here:
        jif_seguro seguro = new jif_seguro();
        desktopPane.add(seguro);
        seguro.setPosicao();
        ((BasicInternalFrameUI)seguro.getUI()).setNorthPane(null);
        seguro.setVisible(true);
    }//GEN-LAST:event_Cad_seguroActionPerformed

    private void Cad_multaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cad_multaActionPerformed
        // TODO add your handling code here:
        jif_multa multa = new jif_multa();
        desktopPane.add(multa);
        multa.setPosicao();
        ((BasicInternalFrameUI)multa.getUI()).setNorthPane(null);
        multa.setVisible(true);
    }//GEN-LAST:event_Cad_multaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Cad_abastecimento;
    private javax.swing.JMenuItem Cad_aluguel;
    private javax.swing.JMenuItem Cad_cliente;
    private javax.swing.JMenuItem Cad_motorista;
    private javax.swing.JMenuItem Cad_multa;
    private javax.swing.JMenuItem Cad_pneu;
    private javax.swing.JMenuItem Cad_seguro;
    private javax.swing.JMenuItem Cad_veiculo;
    private javax.swing.JMenu CadastroMenu;
    private javax.swing.JMenu ConsultaMenu;
    private javax.swing.JMenu SolicitaMenu;
    private javax.swing.JMenuItem consultaCliente;
    private javax.swing.JMenuItem consultaMotorista;
    private javax.swing.JMenuItem consultaVeiculo;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem solicitaManutencao;
    private javax.swing.JMenuItem solicitaViagem;
    // End of variables declaration//GEN-END:variables

}
